(()=>{
"use strict";
const DB_NAME="vibecode-cartas-tcg-v2",STORE_COLLECTIONS="collections";
const objectUrls=new Map();
const urlFor=blob=>{if(!blob)return"";if(!objectUrls.has(blob))objectUrls.set(blob,URL.createObjectURL(blob));return objectUrls.get(blob)};
const globalValue=name=>{try{return window.eval(name)}catch{return null}};
const cardsNow=()=>globalValue("cards")||[];
const collectionsNow=()=>globalValue("collections")||[];
const franchisesNow=()=>globalValue("franchises")||[];
let selectedCardId=localStorage.getItem("vibecode-cartas-tcg-layout-example")||"";
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveCollectionAssets(id,front,back){const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE_COLLECTIONS,"readwrite"),st=tx.objectStore(STORE_COLLECTIONS),g=st.get(id);g.onsuccess=()=>{const value=g.result;if(!value)return reject(new Error("Coleção não encontrada."));if(front)value.front=front;if(back)value.back=back;st.put(value)};g.onerror=()=>reject(g.error);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
function effectiveData(card){const collections=collectionsNow(),franchises=franchisesNow(),collection=collections.find(x=>x.id===card?.collectionId),franchise=franchises.find(x=>x.id===collection?.franchiseId);return{card,collection,franchise,front:collection?.front||card?.front||null,back:collection?.back||card?.back||null,art:card?.art||null,logo:franchise?.logo||null}}
window.__getLayoutExampleData=()=>{const cards=cardsNow();let card=cards.find(x=>x.id===selectedCardId)||cards[0]||null;if(card&&!selectedCardId){selectedCardId=card.id;localStorage.setItem("vibecode-cartas-tcg-layout-example",selectedCardId)}const d=effectiveData(card);return{cardId:card?.id||"",frontBg:urlFor(d.front),backBg:urlFor(d.back),art:urlFor(d.art),logo:urlFor(d.logo),backLogo:urlFor(d.logo),name:card?.name||"Nome da carta",meta:[d.collection?.name||"Coleção",card?.number?(d.collection?.total?card.number+"/"+d.collection.total:card.number):"—"],backText:d.franchise?.name||"TCG"}};
function buildExampleSelector(){const layout=document.querySelector("#layout .panel");if(!layout)return;let wrap=document.querySelector("#layout-example-wrap");if(!wrap){wrap=document.createElement("label");wrap.id="layout-example-wrap";wrap.textContent="Carta de exemplo";const select=document.createElement("select");select.id="layout-example";select.addEventListener("change",()=>{selectedCardId=select.value;localStorage.setItem("vibecode-cartas-tcg-layout-example",selectedCardId);window.renderLayoutPreview?.()});wrap.append(select);layout.insertBefore(wrap,document.querySelector("#picker"))}const select=wrap.querySelector("select"),cards=cardsNow();const current=selectedCardId;select.replaceChildren();if(!cards.length){select.add(new Option("Nenhuma carta cadastrada",""));select.disabled=true}else{select.disabled=false;cards.forEach(card=>{const d=effectiveData(card);select.add(new Option((d.collection?.name?d.collection.name+" · ":"")+card.name,card.id))});select.value=cards.some(x=>x.id===current)?current:cards[0].id;selectedCardId=select.value;localStorage.setItem("vibecode-cartas-tcg-layout-example",selectedCardId)}}
function buildCollectionAssetsPanel(){const section=document.querySelector("#collections");if(!section||document.querySelector("#collection-assets"))return;const panel=document.createElement("section");panel.id="collection-assets";panel.className="panel";panel.innerHTML='<h2>Fundos da coleção</h2><p class="help">Estes fundos são usados por todas as cartas da coleção. Fundos antigos salvos por carta permanecem como fallback.</p><div class="grid"><label>Coleção<select id="asset-collection"></select></label><label>Fundo frontal<input id="asset-front" type="file" accept="image/*"></label><label>Fundo traseiro<input id="asset-back" type="file" accept="image/*"></label></div><div class="actions"><button id="save-assets" type="button" class="primary">Salvar fundos</button></div><div id="asset-status" class="status"></div>';
section.insertBefore(panel,section.lastElementChild);panel.querySelector("#save-assets").onclick=async()=>{const id=panel.querySelector("#asset-collection").value,status=panel.querySelector("#asset-status");if(!id){status.textContent="Selecione uma coleção.";return}try{await saveCollectionAssets(id,panel.querySelector("#asset-front").files[0],panel.querySelector("#asset-back").files[0]);status.textContent="Fundos da coleção salvos.";panel.querySelector("#asset-front").value=panel.querySelector("#asset-back").value="";const refresh=globalValue("refresh");await refresh?.();setTimeout(()=>{populateCollectionSelect();buildExampleSelector();window.renderLayoutPreview?.()},0)}catch(error){status.textContent=error.message}};populateCollectionSelect()}
function populateCollectionSelect(){const select=document.querySelector("#asset-collection");if(!select)return;const old=select.value;select.replaceChildren(new Option("Selecione",""));collectionsNow().forEach(c=>{const f=franchisesNow().find(x=>x.id===c.franchiseId);select.add(new Option((f?f.name+" · ":"")+c.name,c.id))});select.value=old}
function hideCardBackgroundInputs(){document.querySelectorAll("#cf label").forEach(label=>{const text=label.firstChild?.textContent?.trim();if(text==="Fundo frontal"||text==="Fundo traseiro")label.hidden=true});const form=document.querySelector("#cf");if(form&&!document.querySelector("#card-bg-note")){const p=document.createElement("p");p.id="card-bg-note";p.className="help";p.textContent="Os fundos frontal e traseiro agora são configurados por coleção.";form.querySelector(".actions")?.before(p)}}
function patchNode(){if(window.__collectionNodePatched)return;const original=globalValue("node");if(typeof original!=="function")return;window.__collectionNodePatched=true;window.__nodeWithCollections=function(card,side="front",printing=false){const d=effectiveData(card),effective={...card,front:d.front,back:d.back};const root=original(effective,side,printing);if(side==="back"&&d.logo){const img=new Image();img.className="back-logo";img.src=urlFor(d.logo);const l=globalValue("layout")||{};Object.assign(img.style,{position:"absolute",left:(l.backLogoX??25)+"%",top:(l.backLogoY??5)+"%",width:(l.backLogoW??50)+"%",height:(l.backLogoH??16)+"%",objectFit:l.backLogoFit||"contain",objectPosition:(l.backLogoPosX??50)+"% "+(l.backLogoPosY??50)+"%",transform:"scale("+((l.backLogoZoom||100)/100)+")",transformOrigin:"50% 50%"});root.append(img)}return root};try{window.eval("node=window.__nodeWithCollections")}catch{} }
function refreshUi(){buildExampleSelector();populateCollectionSelect();patchNode()}
function install(){hideCardBackgroundInputs();buildCollectionAssetsPanel();buildExampleSelector();patchNode();document.querySelectorAll('.tab[data-v="layout"],.tab[data-v="collections"]').forEach(button=>button.addEventListener("click",()=>setTimeout(refreshUi,50)));setInterval(refreshUi,1500);const footer=document.querySelector("#ver");if(footer)footer.textContent="Cartas TCG · v1.6.0 · editor SVG"}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
addEventListener("pagehide",()=>objectUrls.forEach(URL.revokeObjectURL));
})();