(()=>{
"use strict";
const NS="http://www.w3.org/2000/svg",KEY="vibecode-cartas-tcg-layout-v2",PRINT_KEY="vibecode-cartas-tcg-print-v1";
const $=s=>document.querySelector(s),svg=(tag,a={})=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(a))n.setAttribute(k,v);return n};
const gv=n=>{try{return window.eval(n)}catch{return null}},cardsNow=()=>gv("cards")||[],collectionsNow=()=>gv("collections")||[],franchisesNow=()=>gv("franchises")||[];
const urls=new Map(),urlFor=b=>{if(!b)return"";if(!urls.has(b))urls.set(b,URL.createObjectURL(b));return urls.get(b)};
const layout=()=>gv("layout")||JSON.parse(localStorage.getItem(KEY)||"{}");
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const box=(l,k)=>({x:(l[k+"X"]??0)*6.3,y:(l[k+"Y"]??0)*8.8,w:(l[k+"W"]??100)*6.3,h:(l[k+"H"]??100)*8.8});
const natural=href=>new Promise(resolve=>{if(!href)return resolve({w:1,h:1});const i=new Image();i.onload=()=>resolve({w:i.naturalWidth||1,h:i.naturalHeight||1});i.onerror=()=>resolve({w:1,h:1});i.src=href});
function effective(card){const co=collectionsNow().find(x=>x.id===card.collectionId),fr=franchisesNow().find(x=>x.id===co?.franchiseId);return{card,co,fr,front:co?.front||card.front||null,back:co?.back||card.back||null,logo:fr?.logo||null}}
function geometry(l,key,b,nw,nh){const mode=l[key+"Fit"]||"cover",zoom=Math.max(.01,(l[key+"Zoom"]||100)/100),px=clamp(l[key+"PosX"]??50,0,100)/100,py=clamp(l[key+"PosY"]??50,0,100)/100;let w,h;if(mode==="fill"){w=b.w;h=b.h}else{const scale=(mode==="contain"?Math.min:Math.max)(b.w/nw,b.h/nh);w=nw*scale;h=nh*scale}w*=zoom;h*=zoom;return{x:b.x+(b.w-w)*px,y:b.y+(b.h-h)*py,w,h}}
async function addImage(root,l,key,href,b,id){if(!href)return;const dim=await natural(href),clip=svg("clipPath",{id}),cr=svg("rect",{x:b.x,y:b.y,width:b.w,height:b.h}),g=geometry(l,key,b,dim.w,dim.h),im=svg("image",{href,x:g.x,y:g.y,width:g.w,height:g.h,preserveAspectRatio:"none","clip-path":`url(#${id})`});clip.append(cr);root.querySelector("defs").append(clip);root.append(im)}
function addText(root,l,key,text,anchor="start"){const b=box(l,key),t=svg("text",{x:anchor==="middle"?b.x+b.w/2:b.x+5,y:b.y+b.h/2,fill:"white","font-size":(l[key+"Size"]||4)*6.3,"font-weight":"800","dominant-baseline":"middle","text-anchor":anchor,style:"paint-order:stroke;stroke:#000;stroke-width:3px;stroke-opacity:.65"});t.textContent=text||"";root.append(t)}
async function renderCard(card,side){const l=layout(),d=effective(card),root=svg("svg",{viewBox:"0 0 630 880",class:"print-svg-card",role:"img"});root.append(svg("defs"),svg("rect",{x:0,y:0,width:630,height:880,rx:24,fill:"#111827"}));const uid=Math.random().toString(36).slice(2);if(side==="front"){await addImage(root,l,"front",urlFor(d.front),{x:0,y:0,w:630,h:880},`pf-${uid}`);await addImage(root,l,"art",urlFor(card.art),box(l,"art"),`pa-${uid}`);await addImage(root,l,"logo",urlFor(d.logo),box(l,"logo"),`pl-${uid}`);addText(root,l,"name",card.name||"Nome da carta");addText(root,l,"meta",`${d.co?.name||"Coleção"}   ${card.number?(d.co?.total?card.number+"/"+d.co.total:card.number):"—"}`)}else{await addImage(root,l,"back",urlFor(d.back),{x:0,y:0,w:630,h:880},`pb-${uid}`);await addImage(root,l,"backLogo",urlFor(d.logo),box(l,"backLogo"),`pbl-${uid}`);addText(root,l,"backText",d.fr?.name||"TCG","middle")}return root}
function state(){try{return{mirror:true,dx:0,dy:0,...JSON.parse(localStorage.getItem(PRINT_KEY)||"{}")}}catch{return{mirror:true,dx:0,dy:0}}}
function saveState(s){localStorage.setItem(PRINT_KEY,JSON.stringify(s))}
function order(items,side,s){if(side!=="back"||!s.mirror)return items;const out=[];for(let i=0;i<items.length;i+=3)out.push(...items.slice(i,i+3).reverse());return out}
function quantities(){const map=new Map();document.querySelectorAll("#svg-print-card-list input[data-card]").forEach(i=>map.set(i.dataset.card,Math.max(0,Math.min(99,Number(i.value)||0))));const out=[];cardsNow().forEach(c=>{for(let n=0;n<(map.get(c.id)??1);n++)out.push(c)});return out}
function buildCardList(){const host=$("#svg-print-card-list");if(!host)return;const old=new Map([...host.querySelectorAll("input[data-card]")].map(i=>[i.dataset.card,i.value]));host.replaceChildren();cardsNow().forEach(c=>{const d=effective(c),row=document.createElement("label"),input=document.createElement("input"),name=document.createElement("span");row.className="svg-print-card-row";input.type="number";input.min="0";input.max="99";input.inputMode="numeric";input.dataset.card=c.id;input.value=old.get(c.id)??"1";name.textContent=`${d.co?.name?d.co.name+" · ":""}${c.name}`;row.append(name,input);host.append(row)})}
async function prepare(side){const s=state(),status=$("#ps"),items=order(quantities(),side,s);if(!items.length){status.textContent="Defina ao menos uma cópia para imprimir.";return}status.textContent="Preparando SVGs…";const nodes=[];for(const card of items)nodes.push(await renderCard(card,side));const sheet=$("#print-sheet"),preview=$("#print-preview");sheet.replaceChildren();preview.replaceChildren();for(let p=0;p<nodes.length;p+=9){const page=document.createElement("section");page.className="svg-print-page";nodes.slice(p,p+9).forEach(n=>{const wrap=document.createElement("div");wrap.className="svg-print-cell";if(side==="back")wrap.style.transform=`translate(${s.dx}mm,${s.dy}mm)`;wrap.append(n);page.append(wrap)});sheet.append(page)}nodes.slice(0,9).forEach(n=>{const w=document.createElement("div");w.className="svg-print-preview-cell";w.append(n.cloneNode(true));preview.append(w)});preview.hidden=false;$("#open-print").hidden=false;status.textContent=`${nodes.length} carta(s) · ${side==="front"?"frentes":"versos"} · SVG unificado.`}
function calibration(){const s=state(),sheet=$("#print-sheet"),preview=$("#print-preview"),page=document.createElement("section");page.className="svg-print-page calibration";for(let i=0;i<9;i++){const c=document.createElement("div");c.className="svg-print-cell calibration-cell";c.innerHTML='<span class="cross tl">+</span><span class="cross tr">+</span><span class="cross bl">+</span><span class="cross br">+</span><strong>63 × 88 mm</strong>';c.style.transform=`translate(${s.dx}mm,${s.dy}mm)`;page.append(c)}sheet.replaceChildren(page);preview.replaceChildren(page.cloneNode(true));preview.hidden=false;$("#open-print").hidden=false;$("#ps").textContent="Folha de calibração preparada."}
function replaceButton(id,handler){const old=$(id);if(!old)return;const b=old.cloneNode(true);old.replaceWith(b);b.addEventListener("click",handler);return b}
function install(){const panel=$("#print .panel");if(!panel||$("#svg-print-options"))return;const s=state(),opts=document.createElement("section");opts.id="svg-print-options";opts.className="controls";opts.innerHTML='<h3>Impressão SVG</h3><div class="control-grid"><label><span>Espelhar colunas no verso</span><input id="print-mirror" type="checkbox"></label><label>Correção horizontal do verso (mm)<input id="print-dx" type="number" step="0.1" min="-10" max="10"></label><label>Correção vertical do verso (mm)<input id="print-dy" type="number" step="0.1" min="-10" max="10"></label></div><h4>Cópias por carta</h4><div id="svg-print-card-list"></div><div class="actions"><button id="print-calibration" type="button">Folha de calibração</button></div>';
panel.querySelector(".actions")?.before(opts);opts.querySelector("#print-mirror").checked=s.mirror;opts.querySelector("#print-dx").value=s.dx;opts.querySelector("#print-dy").value=s.dy;const persist=()=>{s.mirror=opts.querySelector("#print-mirror").checked;s.dx=Number(opts.querySelector("#print-dx").value)||0;s.dy=Number(opts.querySelector("#print-dy").value)||0;saveState(s)};opts.querySelectorAll("input").forEach(i=>i.addEventListener("change",persist));opts.querySelector("#print-calibration").onclick=()=>{persist();calibration()};buildCardList();replaceButton("#prepare-front",()=>{persist();prepare("front")});replaceButton("#prepare-back",()=>{persist();prepare("back")});replaceButton("#open-print",()=>window.print());document.querySelectorAll('.tab[data-v="print"]').forEach(b=>b.addEventListener("click",()=>setTimeout(buildCardList,0)));const style=document.createElement("style");style.textContent='#svg-print-card-list{display:grid;gap:6px;max-height:240px;overflow:auto}.svg-print-card-row{display:grid;grid-template-columns:1fr 70px;align-items:center;gap:8px;padding:8px;background:#0f172a;border-radius:10px}.svg-print-card-row input{padding:8px}.svg-print-preview-cell{aspect-ratio:63/88;overflow:hidden}.print-svg-card{display:block;width:100%;height:100%}@page{size:A4 portrait;margin:6mm}@media print{#print-sheet{display:block!important;width:auto!important}.svg-print-page{width:191mm;height:268mm;display:grid;grid-template-columns:repeat(3,63mm);grid-template-rows:repeat(3,88mm);column-gap:1mm;row-gap:2mm;break-after:page;page-break-after:always}.svg-print-page:last-child{break-after:auto;page-break-after:auto}.svg-print-cell{width:63mm;height:88mm;overflow:hidden;border:.2mm solid #777;box-sizing:border-box}.calibration-cell{position:relative;display:grid;place-items:center;color:#000;border:.25mm solid #000}.cross{position:absolute;font-size:5mm}.tl{left:1mm;top:0}.tr{right:1mm;top:0}.bl{left:1mm;bottom:0}.br{right:1mm;bottom:0}}';document.head.append(style);const footer=$("#ver");if(footer)footer.textContent="Cartas TCG · v1.7.0 · impressão SVG"}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
addEventListener("pagehide",()=>urls.forEach(URL.revokeObjectURL));
})();