(()=>{
"use strict";
const NS="http://www.w3.org/2000/svg",KEY="vibecode-cartas-tcg-layout-v2";
const defs={art:["Ilustração","front","boxImage"],logo:["Logo frontal","front","boxImage"],name:["Nome","front","text"],meta:["Rodapé","front","text"],front:["Fundo frontal","front","background"],back:["Fundo traseiro","back","background"],backLogo:["Logo da franquia no verso","back","boxImage"],backText:["Texto do verso","back","text"]};
const defaults={artX:7,artY:16,artW:86,artH:58,artFit:"cover",artPosX:50,artPosY:50,artZoom:100,frontFit:"cover",frontPosX:50,frontPosY:50,frontZoom:100,backFit:"cover",backPosX:50,backPosY:50,backZoom:100,logoX:70,logoY:4,logoW:25,logoH:9,logoFit:"contain",logoPosX:50,logoPosY:50,logoZoom:100,backLogoX:25,backLogoY:5,backLogoW:50,backLogoH:16,backLogoFit:"contain",backLogoPosX:50,backLogoPosY:50,backLogoZoom:100,nameX:6,nameY:5,nameW:62,nameH:8,nameSize:4.5,metaX:6,metaY:90,metaW:88,metaH:6,metaSize:3.2,backTextX:15,backTextY:40,backTextW:70,backTextH:20,backTextSize:6};
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let selected="art",installed=false,gesture=null,raf=0;const pointers=new Map(),refs=new Map();
function globalValue(name){try{return window.eval(name)}catch{return null}}
function layoutRef(){const l=globalValue("layout");if(l){for(const[k,v]of Object.entries(defaults))if(l[k]===undefined)l[k]=v;return l}try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return{...defaults}}}
function persist(){localStorage.setItem(KEY,JSON.stringify(layoutRef()))}
function svg(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n}
function data(){try{return window.__getLayoutExampleData?.()||{}}catch{return{}}}
function box(key){const l=layoutRef();return{x:(l[key+"X"]??0)*6.3,y:(l[key+"Y"]??0)*8.8,w:(l[key+"W"]??100)*6.3,h:(l[key+"H"]??100)*8.8}}
function imageGeometry(key,b,r){const l=layoutRef(),nw=Math.max(1,r.nw||b.w),nh=Math.max(1,r.nh||b.h),mode=l[key+"Fit"]||"cover",zoom=Math.max(.01,(l[key+"Zoom"]||100)/100),px=clamp(l[key+"PosX"]??50,0,100)/100,py=clamp(l[key+"PosY"]??50,0,100)/100;let rw,rh;if(mode==="fill"){rw=b.w;rh=b.h}else{const scale=(mode==="contain"?Math.min:Math.max)(b.w/nw,b.h/nh);rw=nw*scale;rh=nh*scale}rw*=zoom;rh*=zoom;return{x:b.x+(b.w-rw)*px,y:b.y+(b.h-rh)*py,w:rw,h:rh}}
function makeImage(root,key,href,b){if(!href)return;const id=`clip-${key}`,clip=svg("clipPath",{id}),clipRect=svg("rect",{x:b.x,y:b.y,width:b.w,height:b.h}),g=svg("g",{"data-key":key,class:"svg-editable"}),hit=svg("rect",{x:b.x,y:b.y,width:b.w,height:b.h,fill:"transparent","pointer-events":"all"}),img=svg("image",{href,"clip-path":`url(#${id})`,preserveAspectRatio:"none"});clip.append(clipRect);root.querySelector("defs").append(clip);g.append(img,hit);root.append(g);const ref={type:"image",g,img,hit,clipRect,side:root.dataset.side,nw:0,nh:0};refs.set(key,ref);const probe=new Image();probe.onload=()=>{ref.nw=probe.naturalWidth||1;ref.nh=probe.naturalHeight||1;updateKey(key)};probe.src=href;updateKey(key)}
function makeText(root,key,text,anchor="start"){const b=box(key),g=svg("g",{"data-key":key,class:"svg-editable"}),hit=svg("rect",{x:b.x,y:b.y,width:b.w,height:b.h,fill:"transparent","pointer-events":"all"}),t=svg("text",{fill:"white","font-weight":"800","dominant-baseline":"middle","text-anchor":anchor,style:"paint-order:stroke;stroke:#000;stroke-width:3px;stroke-opacity:.65;pointer-events:none"});t.textContent=text||"";g.append(hit,t);root.append(g);refs.set(key,{type:"text",g,hit,t,anchor,side:root.dataset.side});updateKey(key)}
function face(side,d){const root=svg("svg",{viewBox:"0 0 630 880",class:"svg-card","data-side":side});root.append(svg("defs"),svg("rect",{x:0,y:0,width:630,height:880,rx:24,fill:"#111827"}));if(side==="front"){makeImage(root,"front",d.frontBg,{x:0,y:0,w:630,h:880});makeImage(root,"art",d.art,box("art"));makeImage(root,"logo",d.logo,box("logo"));makeText(root,"name",d.name||"Nome da carta");makeText(root,"meta",d.meta?.join("   ")||"Coleção   —")}else{makeImage(root,"back",d.backBg,{x:0,y:0,w:630,h:880});makeImage(root,"backLogo",d.backLogo,box("backLogo"));makeText(root,"backText",d.backText||"TCG","middle")}root.addEventListener("pointerdown",down,{passive:false});root.addEventListener("dblclick",dbl);return root}
function rebuild(){const front=$("#layout-front"),back=$("#layout-back");if(!front||!back)return;refs.clear();const d=data();front.replaceChildren(face("front",d));back.replaceChildren(face("back",d));mark();buildControls(false)}
function updateKey(key){const r=refs.get(key);if(!r)return;const l=layoutRef(),b=defs[key][2]==="background"?{x:0,y:0,w:630,h:880}:box(key);if(r.type==="image"){for(const n of[r.hit,r.clipRect]){n.setAttribute("x",b.x);n.setAttribute("y",b.y);n.setAttribute("width",b.w);n.setAttribute("height",b.h)}const g=imageGeometry(key,b,r);r.img.setAttribute("x",g.x);r.img.setAttribute("y",g.y);r.img.setAttribute("width",g.w);r.img.setAttribute("height",g.h);r.img.removeAttribute("transform")}else{r.hit.setAttribute("x",b.x);r.hit.setAttribute("y",b.y);r.hit.setAttribute("width",b.w);r.hit.setAttribute("height",b.h);r.t.setAttribute("x",r.anchor==="middle"?b.x+b.w/2:b.x+5);r.t.setAttribute("y",b.y+b.h/2);r.t.setAttribute("font-size",(l[key+"Size"]||4)*6.3)}}
function mark(){for(const[key,r]of refs)r.g.classList.toggle("selected",key===selected);document.querySelectorAll("#picker button").forEach(b=>b.classList.toggle("active",b.dataset.key===selected))}
function picker(){const host=$("#picker");if(!host)return;host.replaceChildren();for(const[key,[label]]of Object.entries(defs)){const b=document.createElement("button");b.type="button";b.dataset.key=key;b.textContent=label;b.onclick=()=>{selected=key;mark();buildControls(false)};host.append(b)}mark()}
function range(label,key,min,max,step=1){const lab=document.createElement("label"),wrap=document.createElement("div"),input=document.createElement("input"),out=document.createElement("output"),l=layoutRef();lab.textContent=label;wrap.className="range";input.type="range";input.min=min;input.max=max;input.step=step;input.value=l[key]??min;out.textContent=input.value;input.oninput=()=>{l[key]=Number(input.value);out.textContent=input.value;if(!raf)raf=requestAnimationFrame(()=>{raf=0;updateKey(selected)})};wrap.append(input,out);lab.append(wrap);return lab}
function selectFit(key){const lab=document.createElement("label"),s=document.createElement("select"),l=layoutRef();lab.textContent="Preenchimento";[["cover","Preencher / recortar"],["contain","Conter inteira"],["fill","Esticar"]].forEach(([v,n])=>s.add(new Option(n,v)));s.value=l[key]||"cover";s.onchange=()=>{l[key]=s.value;updateKey(selected)};lab.append(s);return lab}
function buildControls(rebuildPicker=true){if(rebuildPicker)picker();const host=$("#layout-controls");if(!host)return;host.replaceChildren();const[label,,type]=defs[selected],boxEl=document.createElement("section"),grid=document.createElement("div"),h=document.createElement("h3");boxEl.className="controls";grid.className="control-grid";h.textContent=label;boxEl.append(h);if(type==="background")grid.append(selectFit(selected+"Fit"),range("Enquadramento X",selected+"PosX",0,100),range("Enquadramento Y",selected+"PosY",0,100),range("Zoom",selected+"Zoom",50,300));else{grid.append(range("Posição X",selected+"X",-20,100),range("Posição Y",selected+"Y",-20,100),range("Largura",selected+"W",3,120),range("Altura",selected+"H",3,120));if(type==="text")grid.append(range("Tamanho do texto",selected+"Size",1,20,.1));else grid.append(selectFit(selected+"Fit"),range("Enquadramento X",selected+"PosX",0,100),range("Enquadramento Y",selected+"PosY",0,100),range("Zoom da imagem",selected+"Zoom",50,300))}boxEl.append(grid);host.append(boxEl);const note=$("#note");if(note)note.textContent=`${label} · arraste para mover/enquadrar · pinça para redimensionar/zoom`}
const pts=()=>[...pointers.values()],distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function resetGestureBase(){if(!gesture)return;const l=layoutRef(),p=pts();gesture.origin=p[0];gesture.distance=p.length>1?distance(p[0],p[1]):0;gesture.start={x:l[gesture.key+"X"]||0,y:l[gesture.key+"Y"]||0,w:l[gesture.key+"W"]||100,h:l[gesture.key+"H"]||100,posX:l[gesture.key+"PosX"]??50,posY:l[gesture.key+"PosY"]??50,zoom:l[gesture.key+"Zoom"]||100}}
function down(ev){ev.preventDefault();const surface=ev.currentTarget;if(defs[selected]?.[1]!==surface.dataset.side)return;surface.setPointerCapture?.(ev.pointerId);pointers.set(ev.pointerId,{x:ev.clientX,y:ev.clientY});if(!gesture){gesture={surface,key:selected,type:defs[selected][2]};surface.addEventListener("pointermove",move,{passive:false});surface.addEventListener("pointerup",end);surface.addEventListener("pointercancel",end)}resetGestureBase()}
function move(ev){if(!gesture||!pointers.has(ev.pointerId))return;ev.preventDefault();pointers.set(ev.pointerId,{x:ev.clientX,y:ev.clientY});const p=pts(),l=layoutRef(),rect=gesture.surface.getBoundingClientRect();if(p.length===1){const dx=(p[0].x-gesture.origin.x)/rect.width*100,dy=(p[0].y-gesture.origin.y)/rect.height*100;if(gesture.type==="background"){l[gesture.key+"PosX"]=clamp(gesture.start.posX-dx,0,100);l[gesture.key+"PosY"]=clamp(gesture.start.posY-dy,0,100)}else{l[gesture.key+"X"]=clamp(gesture.start.x+dx,-20,100);l[gesture.key+"Y"]=clamp(gesture.start.y+dy,-20,100)}}else{const ratio=distance(p[0],p[1])/(gesture.distance||1);if(gesture.type==="background")l[gesture.key+"Zoom"]=clamp(gesture.start.zoom*ratio,50,300);else{l[gesture.key+"W"]=clamp(gesture.start.w*ratio,3,120);l[gesture.key+"H"]=clamp(gesture.start.h*ratio,3,120)}}if(!raf)raf=requestAnimationFrame(()=>{raf=0;updateKey(gesture.key)})}
function end(ev){pointers.delete(ev.pointerId);if(pointers.size){resetGestureBase();return}if(gesture){const s=gesture.surface;s.removeEventListener("pointermove",move);s.removeEventListener("pointerup",end);s.removeEventListener("pointercancel",end);gesture=null;buildControls(false)}}
function dbl(ev){const key=ev.target.closest?.("[data-key]")?.dataset.key;if(key){selected=key;mark();buildControls(false)}}
function install(){if(installed)return;installed=true;const style=document.createElement("style");style.textContent=".layout-preview{aspect-ratio:63/88;background:#111827}.svg-card{display:block;width:100%;height:100%;touch-action:none;border-radius:4.5%;overflow:hidden}.svg-editable{cursor:move}.svg-editable.selected{filter:drop-shadow(0 0 3px #fbbf24)}";document.head.append(style);picker();const save=$("#save-layout"),reset=$("#reset-layout");if(save)save.onclick=()=>{persist();$("#layout-status").textContent="Layout salvo."};if(reset)reset.onclick=()=>{const l=layoutRef();Object.keys(l).forEach(k=>delete l[k]);Object.assign(l,defaults);persist();rebuild();$("#layout-status").textContent="Layout padrão restaurado."};window.renderLayoutPreview=rebuild;window.renderLayout=rebuild;document.querySelectorAll('.tab[data-v="layout"]').forEach(t=>t.addEventListener("click",()=>setTimeout(rebuild,0)));setTimeout(rebuild,100)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
})();