(()=>{
"use strict";
const NS="http://www.w3.org/2000/svg",KEY="vibecode-cartas-tcg-layout-v2";
const defs={art:["Ilustração","front","boxImage"],logo:["Logo frontal","front","boxImage"],name:["Nome","front","text"],meta:["Rodapé","front","text"],front:["Fundo frontal","front","background"],back:["Fundo traseiro","back","background"],backLogo:["Logo da franquia no verso","back","boxImage"],backText:["Texto do verso","back","text"]};
const defaults={artX:7,artY:16,artW:86,artH:58,artFit:"cover",artPosX:50,artPosY:50,artZoom:100,frontFit:"cover",frontPosX:50,frontPosY:50,frontZoom:100,backFit:"cover",backPosX:50,backPosY:50,backZoom:100,logoX:70,logoY:4,logoW:25,logoH:9,logoFit:"contain",logoPosX:50,logoPosY:50,logoZoom:100,backLogoX:25,backLogoY:5,backLogoW:50,backLogoH:16,backLogoFit:"contain",backLogoPosX:50,backLogoPosY:50,backLogoZoom:100,nameX:6,nameY:5,nameW:62,nameH:8,nameSize:4.5,metaX:6,metaY:90,metaW:88,metaH:6,metaSize:3.2,backTextX:15,backTextY:40,backTextW:70,backTextH:20,backTextSize:6};
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let selected="art",pointers=new Map(),gesture=null,raf=0,installed=false;
function globalValue(name){try{return window.eval(name)}catch{return null}}
function layoutRef(){const l=globalValue("layout");if(l){for(const [k,v] of Object.entries(defaults))if(l[k]===undefined)l[k]=v;return l}try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return{...defaults}}}
function persist(){localStorage.setItem(KEY,JSON.stringify(layoutRef()))}
function svg(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs)){if(k==="href")n.setAttributeNS("http://www.w3.org/1999/xlink","href",v);else n.setAttribute(k,v)}return n}
function fallbackSnapshot(){const old=window.renderLayoutPreview;try{if(old&&old!==render)old()}catch{}const f=$("#layout-front"),b=$("#layout-back");return{frontBg:f?.querySelector(".bg")?.src||"",art:f?.querySelector(".art")?.src||"",logo:f?.querySelector(".logo")?.src||"",backLogo:b?.querySelector(".back-logo")?.src||f?.querySelector(".logo")?.src||"",name:f?.querySelector(".name")?.textContent||"Nome da carta",meta:[...(f?.querySelector(".meta")?.children||[])].map(x=>x.textContent),backBg:b?.querySelector(".bg")?.src||"",backText:b?.querySelector(".backmark")?.textContent||"TCG"}}
function snapshot(){try{return window.__getLayoutExampleData?.()||fallbackSnapshot()}catch{return fallbackSnapshot()}}
function fitValue(v){return v==="contain"?"xMidYMid meet":v==="fill"?"none":"xMidYMid slice"}
function imageNode(key,href,x,y,w,h){const l=layoutRef(),clipId="clip-"+key+"-"+Math.random().toString(16).slice(2),g=svg("g",{"data-key":key,class:"svg-editable"}),defsNode=svg("defs"),clip=svg("clipPath",{id:clipId});clip.append(svg("rect",{x,y,width:w,height:h}));defsNode.append(clip);g.append(defsNode);const img=svg("image",{href,x,y,width:w,height:h,"clip-path":`url(#${clipId})`,preserveAspectRatio:fitValue(l[key+"Fit"])}),z=(l[key+"Zoom"]||100)/100,dx=((l[key+"PosX"]??50)-50)*w/100,dy=((l[key+"PosY"]??50)-50)*h/100,cx=x+w/2,cy=y+h/2;img.setAttribute("transform",`translate(${dx} ${dy}) translate(${cx} ${cy}) scale(${z}) translate(${-cx} ${-cy})`);g.append(img);return g}
function textNode(key,text,x,y,w,h,size,anchor="start"){const g=svg("g",{"data-key":key,class:"svg-editable"}),r=svg("rect",{x,y,width:w,height:h,fill:"transparent"}),t=svg("text",{x:anchor==="middle"?x+w/2:x+5,y:y+h/2,"font-size":size,"font-weight":"800",fill:"white","text-anchor":anchor,"dominant-baseline":"middle",style:"paint-order:stroke;stroke:#000;stroke-width:3px;stroke-opacity:.65"});t.textContent=text;g.append(r,t);return g}
function buildFace(side,data){const l=layoutRef(),root=svg("svg",{viewBox:"0 0 630 880",class:"svg-card","data-side":side,role:"img"});root.append(svg("rect",{x:0,y:0,width:630,height:880,rx:24,fill:"#111827"}));if(side==="front"){if(data.frontBg)root.append(imageNode("front",data.frontBg,0,0,630,880));if(data.art)root.append(imageNode("art",data.art,l.artX*6.3,l.artY*8.8,l.artW*6.3,l.artH*8.8));if(data.logo)root.append(imageNode("logo",data.logo,l.logoX*6.3,l.logoY*8.8,l.logoW*6.3,l.logoH*8.8));root.append(textNode("name",data.name,l.nameX*6.3,l.nameY*8.8,l.nameW*6.3,l.nameH*8.8,l.nameSize*6.3));root.append(textNode("meta",data.meta?.length?data.meta.join("   "):"Coleção   —",l.metaX*6.3,l.metaY*8.8,l.metaW*6.3,l.metaH*8.8,l.metaSize*6.3))}else{if(data.backBg)root.append(imageNode("back",data.backBg,0,0,630,880));if(data.backLogo)root.append(imageNode("backLogo",data.backLogo,l.backLogoX*6.3,l.backLogoY*8.8,l.backLogoW*6.3,l.backLogoH*8.8));root.append(textNode("backText",data.backText,l.backTextX*6.3,l.backTextY*8.8,l.backTextW*6.3,l.backTextH*8.8,l.backTextSize*6.3,"middle"))}root.addEventListener("pointerdown",pointerDown,{passive:false});root.addEventListener("dblclick",doubleSelect);return root}
function render(){const data=snapshot(),front=$("#layout-front"),back=$("#layout-back");if(!front||!back)return;front.replaceChildren(buildFace("front",data));back.replaceChildren(buildFace("back",data));markSelection();buildControls()}
function markSelection(){document.querySelectorAll(".svg-editable").forEach(n=>n.classList.toggle("selected",n.dataset.key===selected))}
function picker(){const host=$("#picker");if(!host)return;host.replaceChildren();for(const[key,[label]]of Object.entries(defs)){const b=document.createElement("button");b.type="button";b.textContent=label;b.className=key===selected?"active":"";b.onclick=()=>{selected=key;render()};host.append(b)}}
function range(label,key,min,max,step=1){const l=document.createElement("label"),wrap=document.createElement("div"),r=document.createElement("input"),o=document.createElement("output"),obj=layoutRef();l.textContent=label;wrap.className="range";r.type="range";r.min=min;r.max=max;r.step=step;r.value=obj[key]??min;o.textContent=r.value;r.oninput=()=>{obj[key]=Number(r.value);o.textContent=r.value;render()};wrap.append(r,o);l.append(wrap);return l}
function selectFit(key){const l=document.createElement("label"),s=document.createElement("select"),obj=layoutRef();l.textContent="Preenchimento";[["cover","Preencher / recortar"],["contain","Conter inteira"],["fill","Esticar"]].forEach(([v,n])=>s.add(new Option(n,v)));s.value=obj[key]||"cover";s.onchange=()=>{obj[key]=s.value;render()};l.append(s);return l}
function buildControls(){picker();const host=$("#layout-controls");if(!host)return;host.replaceChildren();const[label,,type]=defs[selected],box=document.createElement("section"),grid=document.createElement("div");box.className="controls";grid.className="control-grid";const h=document.createElement("h3");h.textContent=label;box.append(h);if(type==="background")grid.append(selectFit(selected+"Fit"),range("Enquadramento X",selected+"PosX",0,100),range("Enquadramento Y",selected+"PosY",0,100),range("Zoom",selected+"Zoom",50,300));else{grid.append(range("Posição X",selected+"X",-20,100),range("Posição Y",selected+"Y",-20,100),range("Largura",selected+"W",3,120),range("Altura",selected+"H",3,120));if(type==="text")grid.append(range("Tamanho do texto",selected+"Size",1,20,.1));else grid.append(selectFit(selected+"Fit"),range("Enquadramento X",selected+"PosX",0,100),range("Enquadramento Y",selected+"PosY",0,100),range("Zoom da imagem",selected+"Zoom",50,300))}box.append(grid);host.append(box);const note=$("#note");if(note)note.textContent=`${label} · seleção bloqueada · arraste para mover/enquadrar · pinça para redimensionar/zoom`}
const pointList=()=>[...pointers.values()],distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),allowedOn=(side,key)=>defs[key]?.[1]===side;
function pointerDown(ev){ev.preventDefault();const surface=ev.currentTarget,side=surface.dataset.side,targetKey=ev.target.closest?.("[data-key]")?.dataset.key;if(targetKey&&ev.detail>=2){selected=targetKey;render();return}if(!allowedOn(side,selected))return;surface.setPointerCapture?.(ev.pointerId);pointers.set(ev.pointerId,{x:ev.clientX,y:ev.clientY});const l=layoutRef(),pts=pointList(),type=defs[selected][2];gesture={surface,key:selected,type,origin:pts[0],distance:pts.length>1?distance(pts[0],pts[1]):0,start:{x:l[selected+"X"]||0,y:l[selected+"Y"]||0,w:l[selected+"W"]||100,h:l[selected+"H"]||100,posX:l[selected+"PosX"]??50,posY:l[selected+"PosY"]??50,zoom:l[selected+"Zoom"]||100}};surface.addEventListener("pointermove",pointerMove,{passive:false});surface.addEventListener("pointerup",pointerEnd);surface.addEventListener("pointercancel",pointerEnd)}
function pointerMove(ev){if(!gesture||!pointers.has(ev.pointerId))return;ev.preventDefault();pointers.set(ev.pointerId,{x:ev.clientX,y:ev.clientY});const pts=pointList(),l=layoutRef(),rect=gesture.surface.getBoundingClientRect();if(pts.length===1){const dx=(pts[0].x-gesture.origin.x)/rect.width*100,dy=(pts[0].y-gesture.origin.y)/rect.height*100;if(gesture.type==="background"){l[gesture.key+"PosX"]=clamp(gesture.start.posX+dx*.65,0,100);l[gesture.key+"PosY"]=clamp(gesture.start.posY+dy*.65,0,100)}else{l[gesture.key+"X"]=clamp(gesture.start.x+dx,-20,100);l[gesture.key+"Y"]=clamp(gesture.start.y+dy,-20,100)}}else{const ratio=distance(pts[0],pts[1])/(gesture.distance||distance(pts[0],pts[1]));if(gesture.type==="background")l[gesture.key+"Zoom"]=clamp(gesture.start.zoom*ratio,50,300);else{l[gesture.key+"W"]=clamp(gesture.start.w*ratio,3,120);l[gesture.key+"H"]=clamp(gesture.start.h*ratio,3,120)}}if(!raf)raf=requestAnimationFrame(()=>{raf=0;render()})}
function pointerEnd(ev){pointers.delete(ev.pointerId);if(!pointers.size&&gesture){gesture.surface.removeEventListener("pointermove",pointerMove);gesture.surface.removeEventListener("pointerup",pointerEnd);gesture.surface.removeEventListener("pointercancel",pointerEnd);gesture=null;buildControls()}}
function doubleSelect(ev){const key=ev.target.closest?.("[data-key]")?.dataset.key;if(key){selected=key;render()}}
function install(){if(installed)return;installed=true;const style=document.createElement("style");style.textContent=".layout-preview{aspect-ratio:63/88;background:#111827}.svg-card{display:block;width:100%;height:100%;touch-action:none;border-radius:4.5%;overflow:hidden}.svg-editable{cursor:move}.svg-editable.selected{filter:drop-shadow(0 0 3px #fbbf24)}";document.head.append(style);const save=$("#save-layout"),reset=$("#reset-layout");if(save)save.onclick=()=>{persist();$("#layout-status").textContent="Layout SVG salvo neste aparelho."};if(reset)reset.onclick=()=>{const l=layoutRef();Object.keys(l).forEach(k=>delete l[k]);Object.assign(l,defaults);persist();render();$("#layout-status").textContent="Layout padrão restaurado."};window.renderLayoutPreview=render;window.renderLayout=render;document.querySelectorAll('.tab[data-v="layout"]').forEach(t=>t.addEventListener("click",()=>setTimeout(render,0)));setTimeout(render,100)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install);else install();
})();