(()=>{
"use strict";
const $=s=>document.querySelector(s),gv=n=>{try{return window.eval(n)}catch{return null}};
const cards=()=>gv("cards")||[],collections=()=>gv("collections")||[],franchises=()=>gv("franchises")||[];
const urls=new Map(),urlFor=b=>{if(!b)return"";if(!urls.has(b))urls.set(b,URL.createObjectURL(b));return urls.get(b)};
function effective(card){const co=collections().find(x=>x.id===card.collectionId),fr=franchises().find(x=>x.id===co?.franchiseId),total=co?.total;return{card,co,fr,frontBg:urlFor(co?.front||card.front),backBg:urlFor(co?.back||card.back),art:urlFor(card.art),backLogo:urlFor(fr?.logo),name:card.name,collection:co?.name||"Coleção",franchise:fr?.name||"",numberTop:String(card.number||"").padStart(3,"0"),numberBottom:card.number?(total?`${card.number}/${total}`:String(card.number)):"—",backText:fr?.name||"TCG"}}
function quantities(){const map=new Map();document.querySelectorAll("#svg-print-card-list input[data-card]").forEach(i=>map.set(i.dataset.card,Math.max(0,Math.min(99,Number(i.value)||0))));const out=[];cards().forEach(c=>{for(let n=0;n<(map.get(c.id)??1);n++)out.push(c)});return out}
function state(){try{return{mirror:true,dx:0,dy:0,...JSON.parse(localStorage.getItem("vibecode-cartas-tcg-print-v1")||"{}")}}catch{return{mirror:true,dx:0,dy:0}}}
function ordered(items,side,s){if(side!=="back"||!s.mirror)return items;const out=[];for(let i=0;i<items.length;i+=3)out.push(...items.slice(i,i+3).reverse());return out}
async function prepare(side){const api=window.__tcgTemplateSVG,status=$("#ps"),s=state(),items=ordered(quantities(),side,s);if(!api){status.textContent="Renderer de template indisponível.";return}if(!items.length){status.textContent="Defina ao menos uma cópia para imprimir.";return}status.textContent="Preparando template SVG…";const nodes=[];for(const card of items){const d=effective(card);nodes.push(side==="front"?await api.renderFront(d):await api.renderBack(d))}const sheet=$("#print-sheet"),preview=$("#print-preview");sheet.replaceChildren();preview.replaceChildren();for(let p=0;p<nodes.length;p+=9){const page=document.createElement("section");page.className="svg-print-page";nodes.slice(p,p+9).forEach(n=>{const wrap=document.createElement("div");wrap.className="svg-print-cell";if(side==="back")wrap.style.transform=`translate(${s.dx}mm,${s.dy}mm)`;wrap.append(n);page.append(wrap)});sheet.append(page)}nodes.slice(0,9).forEach(n=>{const w=document.createElement("div");w.className="svg-print-preview-cell";w.append(n.cloneNode(true));preview.append(w)});preview.hidden=false;$("#open-print").hidden=false;status.textContent=`${nodes.length} carta(s) · ${side==="front"?"frentes":"versos"} · template SVG.`}
function replace(id,side){const old=$(id);if(!old)return;const b=old.cloneNode(true);old.replaceWith(b);b.addEventListener("click",()=>prepare(side))}
function install(){replace("#prepare-front","front");replace("#prepare-back","back");const footer=$("#ver");if(footer)footer.textContent="Cartas TCG · v1.8.0 · template SVG"}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(install,100),{once:true});else setTimeout(install,100);
addEventListener("pagehide",()=>urls.forEach(URL.revokeObjectURL));
})();