import{CopileoAI,CopileoAIError,StaticTokenCredentialsProvider}from'./copileo-ai.js';
const APP_VERSION='0.2.0',STORE='vibecode-card-translator-v1',HISTORY='vibecode-card-translator-history-v2',DEFAULT_URL='https://vibecoding-ai-api.copileo.workers.dev',$=id=>document.getElementById(id);let settings=load(STORE,{url:DEFAULT_URL,token:'',model:'gpt-5.4-nano',saveImages:true}),images={front:null,back:null},urls={front:null,back:null},reviewSide='front',resultSide='front',currentResult=null;
const PROMPT=`Translate the photographed board-game card from English into Brazilian Portuguese for immediate use during gameplay. Preserve exact rules, choices, numbers, codes, reading order and visible emphasis. Return valid JSON only: {"title":{"original":"","translated":""},"cardId":"","side":"","sections":[{"type":"narrative|dialogue|rules|choice|identifier|other","original":"","translated":"","originalSegments":[{"text":"","bold":false,"italic":false}],"translatedSegments":[{"text":"","bold":false,"italic":false}]}],"warnings":[{"type":"unreadable|uncertain|unknown_symbol","message":""}]}. Use segments when bold or italic formatting is visible. Do not invent emphasis or unreadable text.`;
try{init()}catch(e){showBootError(e)}
function init(){$('version').textContent=`v${APP_VERSION}`;bind();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));show(settings.token?'home':'setup');fillSetup();renderRecent()}
function bind(){$('camera-input').onchange=e=>pick(e,'front');$('gallery-input').onchange=e=>pick(e,'front');$('back-input').onchange=e=>pick(e,'back');$('retake').onclick=retake;$('add-back').onclick=()=>$('back-input').click();$('translate').onclick=translateBoth;$('another').onclick=resetCapture;$('large-text').onclick=()=>$('translation').classList.toggle('large');$('test-api').onclick=testConnection;$('save-settings').onclick=saveSetup;$('settings-open').onclick=openSettings;$('settings-save').onclick=saveDialog;$('forget-token').onclick=forgetToken;$('clear-history').onclick=clearHistory;document.querySelectorAll('[data-review-side]').forEach(b=>b.onclick=()=>showReviewSide(b.dataset.reviewSide));document.querySelectorAll('[data-result-side]').forEach(b=>b.onclick=()=>showResultSide(b.dataset.resultSide))}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.hidden=true);$(id).hidden=false;scrollTo(0,0)}function showBootError(e){$('setup').hidden=false;$('setup-status').textContent=`Falha ao iniciar: ${e?.message||'erro desconhecido'}`}
async function pick(e,side){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{images[side]=await prepareImage(file);if(urls[side])URL.revokeObjectURL(urls[side]);urls[side]=URL.createObjectURL(images[side]);reviewSide=side;showReviewSide(side);show('review')}catch(err){alert(messageFor(err))}}
async function prepareImage(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Selecione JPEG, PNG ou WebP.');const bitmap=await createImageBitmap(file),max=1600,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return await new Promise((r,j)=>canvas.toBlob(b=>b?r(b):j(Error('Falha ao preparar imagem.')),'image/jpeg',.86))}
function showReviewSide(side){if(!images[side]){if(side==='back')$('back-input').click();return}reviewSide=side;$('preview').src=urls[side];document.querySelectorAll('[data-review-side]').forEach(b=>b.classList.toggle('active',b.dataset.reviewSide===side));$('review-hint').textContent=images.back?'Frente e verso prontos para tradução.':'Você pode traduzir apenas a frente ou adicionar o verso.';$('add-back').textContent=images.back?'Trocar verso':'Adicionar verso'}
function retake(){if(reviewSide==='back')$('back-input').click();else $('camera-input').click()}
function client(){if(!settings.token)throw Error('Configure o token.');return new CopileoAI({gatewayUrl:settings.url,defaultModel:settings.model,timeoutMs:60000,credentialsProvider:new StaticTokenCredentialsProvider(settings.token)})}
async function translateBoth(){if(!images.front)return;show('loading');try{const out={front:null,back:null};$('loading-label').textContent='Traduzindo frente…';out.front=await translateSide(images.front);if(images.back){$('loading-label').textContent='Traduzindo verso…';out.back=await translateSide(images.back)}currentResult={front:out.front,back:out.back,createdAt:new Date().toISOString()};saveHistory(currentResult);showResultSide('front');$('result-side-tabs').hidden=!out.back;show('result')}catch(e){show('review');alert(messageFor(e))}}
async function translateSide(image){const response=await client().chatWithImage({prompt:PROMPT,image,detail:'high'}),text=response?.data?.content;if(typeof text!=='string')throw Error('Resposta sem conteúdo.');const parsed=JSON.parse(text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,''));if(!Array.isArray(parsed.sections))throw Error('Formato de tradução inválido.');parsed.warnings=Array.isArray(parsed.warnings)?parsed.warnings:[];return parsed}
function showResultSide(side){const data=currentResult?.[side];if(!data)return;resultSide=side;document.querySelectorAll('[data-result-side]').forEach(b=>b.classList.toggle('active',b.dataset.resultSide===side));$('result-title').textContent=data.title?.translated||data.cardId||'Tradução';$('result-meta').textContent=[side==='front'?'Frente':'Verso',data.cardId,data.side&&`Lado ${data.side}`].filter(Boolean).join(' · ');$('translation').innerHTML=data.sections.map(s=>`<section class="section ${safeType(s.type)}">${renderTranslated(s)}</section>`).join('');$('original').innerHTML=data.sections.map(s=>`<section class="section">${renderOriginal(s)}</section>`).join('');$('warnings').hidden=!data.warnings.length;$('warnings').innerHTML=data.warnings.map(w=>`<div>${esc(w.message||'Trecho incerto.')}</div>`).join('')}
function renderTranslated(s){return renderSegments(s.translatedSegments)||paragraphs(s.translated)}function renderOriginal(s){return renderSegments(s.originalSegments)||paragraphs(s.original)}function renderSegments(a){if(!Array.isArray(a)||!a.length)return'';return`<p>${a.map(x=>{let t=esc(x.text||'');if(x.bold)t=`<strong>${t}</strong>`;if(x.italic)t=`<em>${t}</em>`;return t}).join('')}</p>`}function paragraphs(t){return String(t||'').split(/\n+/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')}function safeType(t){return['narrative','dialogue','rules','choice','identifier','other'].includes(t)?t:'other'}
function saveHistory(result){const list=load(HISTORY,[]),front=result.front,item={id:crypto.randomUUID(),createdAt:result.createdAt,cardId:front.cardId||'',title:front.title?.translated||'Tradução',result};localStorage.setItem(HISTORY,JSON.stringify([item,...list].slice(0,30)));renderRecent()}
function renderRecent(){const list=load(HISTORY,[]);$('recent-section').hidden=!list.length;$('recent-list').innerHTML=list.map((x,i)=>`<button class="recent-item" data-i="${i}"><strong>${esc(x.title)}</strong><span>${esc(x.cardId||'Carta sem código')}${x.result.back?' · frente e verso':''}</span></button>`).join('');$('recent-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{currentResult=list[+b.dataset.i].result;$('result-side-tabs').hidden=!currentResult.back;showResultSide('front');show('result')})}
function clearHistory(){if(confirm('Apagar histórico?')){localStorage.removeItem(HISTORY);renderRecent()}}function resetCapture(){images={front:null,back:null};urls={front:null,back:null};currentResult=null;show('home');setTimeout(()=>$('camera-input').click(),80)}
function fillSetup(){$('api-url').value=settings.url;$('api-token').value=settings.token;$('model').value=settings.model}async function testConnection(){try{$('setup-status').textContent='Testando…';const c=new CopileoAI({gatewayUrl:$('api-url').value.trim()||DEFAULT_URL,credentialsProvider:new StaticTokenCredentialsProvider($('api-token').value.trim())});await c.models();$('setup-status').textContent='Conexão funcionando.'}catch(e){$('setup-status').textContent=messageFor(e)}}
function saveSetup(){settings={...settings,url:$('api-url').value.trim()||DEFAULT_URL,token:$('api-token').value.trim(),model:$('model').value.trim()||'gpt-5.4-nano'};if(!settings.token)return $('setup-status').textContent='Informe o token.';save(STORE,settings);show('home')}function openSettings(){$('settings-url').value=settings.url;$('settings-token').value=settings.token;$('settings-model').value=settings.model;$('save-images').checked=settings.saveImages;$('settings-dialog').showModal()}function saveDialog(e){e.preventDefault();settings={url:$('settings-url').value.trim()||DEFAULT_URL,token:$('settings-token').value.trim(),model:$('settings-model').value.trim()||'gpt-5.4-nano',saveImages:$('save-images').checked};save(STORE,settings);$('settings-dialog').close()}function forgetToken(){settings.token='';save(STORE,settings);$('settings-dialog').close();fillSetup();show('setup')}
function messageFor(e){if(e instanceof CopileoAIError){if(e.status===401)return'Token inválido ou expirado.';if(e.code==='TIMEOUT')return'A API demorou demais.';if(e.code==='NETWORK_ERROR')return'Não foi possível acessar a AI API.'}return e?.message||'Erro inesperado.'}function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
