import {
  CopileoAI,
  CopileoAIError,
  StaticTokenCredentialsProvider,
} from '../../packages/copileo-ai/src/index.js';

const APP_VERSION='0.1.1';const STORE='vibecode-card-translator-v1';const HISTORY='vibecode-card-translator-history-v1';const DEFAULT_URL='https://vibecoding-ai-api.copileo.workers.dev';const $=id=>document.getElementById(id);let settings=load(STORE,{url:DEFAULT_URL,token:'',model:'gpt-5.4-nano',saveImages:true});let selectedImage=null;let selectedUrl=null;let currentResult=null;

const SYSTEM_PROMPT=`You translate photographed fantasy board-game cards from English into Brazilian Portuguese for immediate use during gameplay.
Priorities: preserve exact mechanical meaning; make Portuguese quick to read; preserve every choice, condition, number, card code, identifier, arrow and ordering; preserve narrative tone.
Read only visible text. Do not invent missing words. Use [ilegível] only when text materially cannot be read. Keep uncertainty outside the translated text when possible.
Never translate card codes such as EVT-37, SML-18, KEY-47, MED-19 or TRV-20. Keep setting-specific creature names unchanged unless a glossary says otherwise. Treat separate text boxes as separate sections. Character choices must remain separate and in order.
Return valid JSON only, with no Markdown, using exactly this shape:
{"title":{"original":"","translated":""},"cardId":"","side":"","sections":[{"type":"narrative|dialogue|rules|choice|identifier|other","original":"","translated":""}],"warnings":[{"type":"unreadable|uncertain|unknown_symbol","message":""}]}
Before answering, verify that numbers, codes and rules match the image.`;

init();
function init(){ $('version').textContent=`v${APP_VERSION}`; bind(); if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{})); show(settings.token?'home':'setup'); renderRecent(); }
function bind(){ $('camera-input').addEventListener('change',pick);$('gallery-input').addEventListener('change',pick);$('retake').onclick=openCamera;$('translate').onclick=translate;$('another').onclick=openCamera;$('large-text').onclick=()=>{$('translation').classList.toggle('large')};$('test-api').onclick=testConnection;$('save-settings').onclick=saveSetup;$('settings-open').onclick=openSettings;$('settings-save').onclick=saveDialog;$('forget-token').onclick=forgetToken;$('clear-history').onclick=clearHistory;window.addEventListener('unhandledrejection',e=>alert(messageFor(e.reason)));}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.hidden=true);$(id).hidden=false;scrollTo(0,0)}
async function pick(event){const file=event.target.files&&event.target.files[0];event.target.value='';if(!file)return;try{selectedImage=await prepareImage(file);if(selectedUrl)URL.revokeObjectURL(selectedUrl);selectedUrl=URL.createObjectURL(selectedImage);$('preview').src=selectedUrl;$('loading-preview').src=selectedUrl;show('review')}catch(e){alert(messageFor(e))}}
function openCamera(){show('home');setTimeout(()=>$('camera-input').click(),80)}
async function prepareImage(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Selecione uma imagem JPEG, PNG ou WebP.');const bitmap=await createImageBitmap(file);const max=1600;const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Não foi possível preparar a imagem.');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let quality=.86,blob=await toBlob(canvas,quality);while(blob.size>2.85*1024*1024&&quality>.62){quality-=.08;blob=await toBlob(canvas,quality)}if(blob.size>3*1024*1024)throw new Error('A foto ficou grande demais. Tente aproximar mais a câmera.');return blob}
function toBlob(canvas,q){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Falha ao codificar a imagem.')),'image/jpeg',q))}
function client(){if(!settings.token)throw new Error('Configure o token da AI API.');return new CopileoAI({gatewayUrl:settings.url,appId:'card-translator',defaultModel:settings.model,timeoutMs:45000,credentialsProvider:new StaticTokenCredentialsProvider(settings.token)})}
async function translate(){if(!selectedImage)return;show('loading');try{const response=await client().chatWithImage({prompt:SYSTEM_PROMPT,image:selectedImage,detail:'high'});const parsed=parseModelResponse(response);validate(parsed);currentResult=parsed;renderResult(parsed);saveHistory(parsed);show('result')}catch(e){show('review');alert(messageFor(e))}}
function parseModelResponse(response){const text=response?.data?.content;if(typeof text!=='string'||!text.trim())throw new Error('A API respondeu, mas response.data.content não contém texto.');const normalized=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(normalized)}catch{throw new Error('A tradução retornou em um formato inválido. Tente novamente.') }}
function validate(x){if(!x||!Array.isArray(x.sections))throw new Error('A tradução não contém as seções esperadas.');x.sections=x.sections.filter(s=>s&&typeof s.translated==='string');x.warnings=Array.isArray(x.warnings)?x.warnings:[];x.title=x.title||{original:'',translated:''}}
function renderResult(x){$('result-title').textContent=x.title?.translated||x.cardId||'Tradução';$('result-meta').textContent=[x.cardId,x.side&&`Lado ${x.side}`].filter(Boolean).join(' · ');$('translation').innerHTML=x.sections.map(s=>`<section class="section ${safeType(s.type)}">${paragraphs(s.translated)}</section>`).join('');$('original').innerHTML=[x.title?.original,...x.sections.map(s=>s.original)].filter(Boolean).map(t=>`<section class="section">${paragraphs(t)}</section>`).join('');$('warnings').hidden=!x.warnings.length;$('warnings').innerHTML=x.warnings.map(w=>`<div>${escapeHtml(w.message||'Trecho incerto na leitura.')}</div>`).join('')}
function paragraphs(text){return String(text||'').split(/\n+/).filter(Boolean).map(p=>`<p>${escapeHtml(p)}</p>`).join('')}
function safeType(t){return ['narrative','dialogue','rules','choice','identifier','other'].includes(t)?t:'other'}
function saveHistory(x){const list=load(HISTORY,[]);const item={id:crypto.randomUUID(),createdAt:new Date().toISOString(),cardId:x.cardId||'',title:x.title?.translated||'Tradução',result:x};if(settings.saveImages&&selectedImage){const reader=new FileReader();reader.onload=()=>{item.thumbnail=reader.result;persistHistory(item,list)};reader.readAsDataURL(selectedImage)}else persistHistory(item,list)}
function persistHistory(item,list){localStorage.setItem(HISTORY,JSON.stringify([item,...list.filter(x=>!(item.cardId&&x.cardId===item.cardId))].slice(0,30)));renderRecent()}
function renderRecent(){const list=load(HISTORY,[]);$('recent-section').hidden=!list.length;$('recent-list').innerHTML=list.map((x,i)=>`<button class="recent-item" data-index="${i}"><strong>${escapeHtml(x.title)}</strong><span>${escapeHtml(x.cardId||'Carta sem código')} · ${relativeTime(x.createdAt)}</span></button>`).join('');$('recent-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{const item=list[Number(b.dataset.index)];currentResult=item.result;renderResult(item.result);show('result')})}
function relativeTime(date){const min=Math.max(0,Math.round((Date.now()-new Date(date))/60000));if(min<1)return'agora';if(min<60)return`${min} min atrás`;const h=Math.round(min/60);return h<24?`${h} h atrás`:new Date(date).toLocaleDateString('pt-BR')}
function clearHistory(){if(confirm('Apagar o histórico de traduções deste dispositivo?')){localStorage.removeItem(HISTORY);renderRecent()}}
function fillSetup(){ $('api-url').value=settings.url;$('api-token').value=settings.token;$('model').value=settings.model }
async function testConnection(){try{const temp=new CopileoAI({gatewayUrl:$('api-url').value.trim()||DEFAULT_URL,appId:'card-translator',defaultModel:$('model').value.trim()||'gpt-5.4-nano',credentialsProvider:new StaticTokenCredentialsProvider($('api-token').value.trim())});$('setup-status').textContent='Testando…';const response=await temp.models();if(!response?.data)throw new Error('A API respondeu sem o envelope esperado.');$('setup-status').textContent='Conexão funcionando.'}catch(e){$('setup-status').textContent=messageFor(e)}}
function saveSetup(){settings={...settings,url:$('api-url').value.trim()||DEFAULT_URL,token:$('api-token').value.trim(),model:$('model').value.trim()||'gpt-5.4-nano'};if(!settings.token){$('setup-status').textContent='Informe o token.';return}save(STORE,settings);show('home')}
function openSettings(){ $('settings-url').value=settings.url;$('settings-token').value=settings.token;$('settings-model').value=settings.model;$('save-images').checked=settings.saveImages;$('settings-dialog').showModal() }
function saveDialog(event){event.preventDefault();settings={url:$('settings-url').value.trim()||DEFAULT_URL,token:$('settings-token').value.trim(),model:$('settings-model').value.trim()||'gpt-5.4-nano',saveImages:$('save-images').checked};save(STORE,settings);$('settings-dialog').close()}
function forgetToken(){settings.token='';save(STORE,settings);$('settings-dialog').close();fillSetup();show('setup')}
function messageFor(e){if(e instanceof CopileoAIError){if(e.status===401||e.code==='UNAUTHORIZED')return'Token inválido ou expirado.';if(e.code==='TIMEOUT')return'A tradução demorou demais. Tente novamente.';if(e.code==='NETWORK_ERROR')return'Não foi possível acessar a AI API. Verifique a conexão.';if(e.code==='PAYLOAD_TOO_LARGE')return'A imagem é grande demais para a AI API.';if(e.code==='RATE_LIMITED')return'Muitas traduções em sequência. Aguarde um momento.';}return e?.message||'Ocorreu um erro inesperado.'}
function load(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}function save(key,value){localStorage.setItem(key,JSON.stringify(value))}function escapeHtml(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
fillSetup();