const APP_VERSION='1.10.0';
const API_BASE=String(window.LUAS_API_BASE||'').replace(/\/$/,'');
const STORAGE_KEY='vibecode-luas-live-v1';
const DEFAULT_QUERIES=[{id:'trinity-brides-glen',stopCode:'tri',stopName:'Trinity',direction:'Outbound',destination:'Brides Glen'}];
const STOP_GROUPS=[
 {label:'Green Line · Broombridge → Brides Glen',stops:[['Broombridge','bro'],['Cabra','cab'],['Phibsborough','phi'],['Grangegorman','gra'],['Broadstone - University','brd'],['Dominick','dom'],['Parnell','par'],["O'Connell - Upper",'ocu'],["O'Connell - GPO",'ocg'],['Marlborough','mar'],['Westmoreland','wes'],['Trinity','tri'],['Dawson','daw'],["St. Stephen's Green",'sti'],['Harcourt','har'],['Charlemont','cha'],['Ranelagh','ran'],['Beechwood','bee'],['Cowper','cow'],['Milltown','mil'],['Windy Arbour','win'],['Dundrum','dun'],['Balally','bal'],['Kilmacud','kil'],['Stillorgan','sti2'],['Sandyford','san'],['Central Park','cen'],['Glencairn','gln'],['The Gallops','gal'],['Leopardstown Valley','leo'],['Ballyogan Wood','bal2'],['Carrickmines','car'],['Laughanstown','lau'],['Cherrywood','che2'],['Brides Glen','bri']]},
 {label:'Red Line · The Point → Tallaght / Saggart',stops:[['The Point','tpt'],['Spencer Dock','sdk'],['Mayor Square - NCI','msq'],["George's Dock",'gdk'],['Connolly','con'],['Busáras','bus'],['Abbey Street','abb'],['Jervis','jer'],['Four Courts','fou'],['Smithfield','smi'],['Museum','mus'],['Heuston','heu'],["James's",'jam'],['Fatima','fat'],['Rialto','ria'],['Suir Road','sui'],['Goldenbridge','gol'],['Drimnagh','dri'],['Blackhorse','bla'],['Bluebell','blu'],['Kylemore','kyl'],['Red Cow','red'],['Kingswood','kin'],['Belgard','bel'],['Tallaght branch',null],['Cookstown','coo'],['Hospital','hos'],['Tallaght','tal'],['Saggart branch',null],['Fettercairn','fet'],['Cheeverstown','che'],['Citywest Campus','cit'],['Fortunestown','for'],['Saggart','sag']]}
];
const stops=STOP_GROUPS.flatMap(group=>group.stops.filter(([,code])=>code).map(([name,code])=>({name,code,line:group.label.startsWith('Green')?'Green':'Red'})));
const boards=document.querySelector('#boards'),emptyState=document.querySelector('#empty-state'),template=document.querySelector('#board-template');
const dialog=document.querySelector('#query-dialog'),form=document.querySelector('#query-form'),stopSelect=document.querySelector('#stop-select'),directionSelect=document.querySelector('#direction-select'),destinationInput=document.querySelector('#destination-input');
const reminderDialog=document.querySelector('#reminder-dialog'),reminderForm=document.querySelector('#reminder-form'),reminderTitle=document.querySelector('#reminder-title'),reminderDetail=document.querySelector('#reminder-detail'),reminderLead=document.querySelector('#reminder-lead'),customLead=document.querySelector('#custom-lead'),reminderStatus=document.querySelector('#reminder-status'),pushReminderButton=document.querySelector('#push-reminder');
const networkStatus=document.querySelector('#network-status'),networkDot=document.querySelector('#network-dot'),versionLabel=document.querySelector('#app-version');
let queries=loadQueries(),boardData=new Map(),pendingReminder=null;
if(versionLabel)versionLabel.textContent=`v${APP_VERSION}`;
function loadQueries(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(value)&&value.length?value:DEFAULT_QUERIES}catch{return DEFAULT_QUERIES}}
function saveQueries(){localStorage.setItem(STORAGE_KEY,JSON.stringify(queries))}
function escapeText(value=''){return String(value).trim()}
async function fetchForecast(stopCode){if(!API_BASE)throw new Error('Realtime API URL is not configured.');const response=await fetch(`${API_BASE}/v1/forecast?stop=${encodeURIComponent(stopCode)}`,{cache:'no-store',headers:{Accept:'application/json'}});if(!response.ok){let detail='';try{const body=await response.json();detail=body.detail||body.error||''}catch{}throw new Error(detail||`Realtime feed unavailable (${response.status}).`)}const data=await response.json();if(!data||data.apiVersion!==1||!Array.isArray(data.departures))throw new Error('The realtime feed returned invalid data.');return data}
function loadStops(){stopSelect.innerHTML=STOP_GROUPS.map(group=>`<optgroup label="${group.label}">${group.stops.map(([name,code])=>code?`<option value="${code}">${name}</option>`:`<option disabled>— ${name} —</option>`).join('')}</optgroup>`).join('');stopSelect.value='tri'}
function parseCreated(value){const date=new Date(value);return Number.isNaN(date.getTime())?new Date():date}
function parseForecast(payload,query){const destination=escapeText(query.destination).toLowerCase(),direction=escapeText(query.direction).toLowerCase(),created=parseCreated(payload.updated);const trams=payload.departures.filter(item=>{const itemDirection=escapeText(item.direction).toLowerCase(),itemDestination=escapeText(item.destination).toLowerCase();return(!direction||itemDirection===direction)&&(!destination||itemDestination.includes(destination))}).map(item=>{const exact=new Date(item.scheduledAt),minutes=Number(item.minutes),scheduledAt=!Number.isNaN(exact.getTime())?exact:(Number.isFinite(minutes)?new Date(created.getTime()+minutes*60000):null);return{destination:item.destination||'Tram',scheduledAt}}).filter(item=>item.scheduledAt).slice(0,3);return{trams,message:payload.message||'Official NTA realtime forecast',created}}
function formatClock(value){return new Intl.DateTimeFormat('en-IE',{hour:'2-digit',minute:'2-digit',hour12:false}).format(value)}
function feedAgeMinutes(created){return Math.max(0,Math.floor((Date.now()-created.getTime())/60000))}
function formatUpdated(created){const age=feedAgeMinutes(created);return`Updated ${formatClock(created)} · ${age}m ago`}
function getRemainingMinutes(scheduledAt){return Math.max(0,Math.ceil((scheduledAt.getTime()-Date.now())/60000))}
function renderSkeleton(query,index){const node=template.content.firstElementChild.cloneNode(true);node.dataset.id=query.id;node.dataset.stopName=query.stopName;node.querySelector('.direction').textContent=query.direction;node.querySelector('.route-title').textContent=`${query.stopName} → ${query.destination||query.direction}`;node.querySelector('.times').innerHTML='<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>';node.querySelector('.message').textContent='Loading realtime forecast…';node.querySelector('.updated').textContent='';const up=node.querySelector('[data-move="up"]'),down=node.querySelector('[data-move="down"]');up.disabled=index===0;down.disabled=index===queries.length-1;up.addEventListener('click',()=>moveQuery(query.id,-1));down.addEventListener('click',()=>moveQuery(query.id,1));node.querySelector('.menu-button').addEventListener('click',()=>removeQuery(query.id));boards.append(node);return node}
function renderForecast(node,data){const active=data.trams.filter(tram=>tram.scheduledAt.getTime()>Date.now()-60000),times=node.querySelector('.times');times.innerHTML=active.length?active.map((tram,index)=>{const remaining=getRemainingMinutes(tram.scheduledAt);return`<button class="time-chip ${remaining===0?'due':''}" type="button" data-reminder-index="${index}" aria-label="Set reminder for ${formatClock(tram.scheduledAt)} to ${tram.destination}"><strong>${remaining===0?'Due':remaining}</strong><span>${formatClock(tram.scheduledAt)} · ${tram.destination}</span><small>Tap to remind</small></button>`}).join(''):'<div class="time-chip"><strong>—</strong><span>No current trams</span></div>';times.querySelectorAll('[data-reminder-index]').forEach(button=>button.addEventListener('click',()=>openReminder(node.dataset.stopName,active[Number(button.dataset.reminderIndex)])));node.querySelector('.message').textContent=data.message;node.querySelector('.updated').textContent=formatUpdated(data.created)}
function rerenderCountdowns(){for(const[id,data]of boardData){const node=boards.querySelector(`[data-id="${CSS.escape(id)}"]`);if(node)renderForecast(node,data)}}
function renderError(node,error){node.querySelector('.times').innerHTML='<div class="time-chip"><strong>!</strong><span>Unavailable</span></div>';node.querySelector('.message').textContent=error.message||'Could not reach the realtime feed';node.querySelector('.updated').textContent='Tap refresh to retry'}
async function refreshBoard(query,node){try{const payload=await fetchForecast(query.stopCode),data=parseForecast(payload,query);boardData.set(query.id,data);renderForecast(node,data);return data}catch(error){boardData.delete(query.id);renderError(node,error);throw error}}
async function refreshAll(){boards.innerHTML='';boardData.clear();emptyState.hidden=queries.length>0;if(!queries.length){networkStatus.textContent='Add a board to check service';networkDot.className='status-dot loading';return}networkStatus.textContent='Checking official realtime service…';networkDot.className='status-dot loading';const cards=queries.map((query,index)=>[query,renderSkeleton(query,index)]),results=await Promise.allSettled(cards.map(([query,node])=>refreshBoard(query,node))),ok=results.filter(result=>result.status==='fulfilled');if(ok.length){networkStatus.textContent='Official NTA realtime data available';networkDot.className='status-dot'}else{networkStatus.textContent='Realtime feed unavailable';networkDot.className='status-dot error'}}
function moveQuery(id,offset){const index=queries.findIndex(query=>query.id===id),target=index+offset;if(index<0||target<0||target>=queries.length)return;[queries[index],queries[target]]=[queries[target],queries[index]];saveQueries();refreshAll()}
function removeQuery(id){queries=queries.filter(query=>query.id!==id);saveQueries();refreshAll()}
function openForm(){dialog.showModal()}
function closeForm(){dialog.close()}
function openReminder(stopName,tram){if(!tram)return;pendingReminder={stopName,tram};reminderTitle.textContent=`${formatClock(tram.scheduledAt)} · ${tram.destination}`;reminderDetail.textContent=`Departure from ${stopName}. Choose a push notification or Calendar alert.`;reminderLead.value='2';customLead.hidden=true;reminderStatus.textContent='Push notifications require Luas Live to be installed on the iPhone Home Screen. Calendar remains available as a fallback.';pushReminderButton.disabled=false;reminderDialog.showModal()}
function closeReminder(){pendingReminder=null;reminderDialog.close()}
function selectedLead(){return reminderLead.value==='custom'?Math.max(0,Math.min(60,Number(customLead.querySelector('input').value)||0)):Number(reminderLead.value)}
function icsDate(date){return date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z')}
function icsEscape(value){return String(value).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function downloadCalendarReminder(stopName,tram,leadMinutes){const start=tram.scheduledAt,end=new Date(start.getTime()+5*60000),uid=`${start.getTime()}-${crypto.randomUUID?.()||Date.now()}@luas-live`,alarm=leadMinutes>0?`-PT${leadMinutes}M`:'PT0M';const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Vibecode//Luas Live//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT',`UID:${uid}`,`DTSTAMP:${icsDate(new Date())}`,`DTSTART:${icsDate(start)}`,`DTEND:${icsDate(end)}`,`SUMMARY:${icsEscape(`Luas from ${stopName} to ${tram.destination}`)}`,`DESCRIPTION:${icsEscape(`Estimated Luas departure at ${formatClock(start)}. Times may change; check Luas Live before leaving.`)}`,`LOCATION:${icsEscape(`${stopName} Luas stop`)}`,'BEGIN:VALARM',`TRIGGER:${alarm}`,'ACTION:DISPLAY',`DESCRIPTION:${icsEscape(`Luas to ${tram.destination} departs ${stopName} at ${formatClock(start)}`)}`,'END:VALARM','END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`luas-${stopName.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${formatClock(start).replace(':','')}.ics`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function urlBase64ToUint8Array(value){const padding='='.repeat((4-value.length%4)%4),base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64);return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)))}
async function schedulePushReminder(){if(!pendingReminder||!API_BASE)return;pushReminderButton.disabled=true;reminderStatus.textContent='Enabling notifications…';try{if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('Push notifications are not supported on this device.');const configResponse=await fetch(`${API_BASE}/push/config`,{headers:{Accept:'application/json'}}),config=await configResponse.json();if(!configResponse.ok||!config.enabled||!config.publicKey)throw new Error(config.error||'Push notifications are not configured on the server.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notification permission was not granted.');const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(config.publicKey)});const lead=selectedLead(),notifyAt=new Date(pendingReminder.tram.scheduledAt.getTime()-lead*60000);if(notifyAt.getTime()<Date.now())throw new Error('That reminder time has already passed.');const response=await fetch(`${API_BASE}/push/reminders`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription:subscription.toJSON(),notifyAt:notifyAt.toISOString(),title:`Luas to ${pendingReminder.tram.destination}`,body:`Departs ${pendingReminder.stopName} at ${formatClock(pendingReminder.tram.scheduledAt)}.`,url:location.href,tag:`luas-${pendingReminder.tram.scheduledAt.getTime()}`})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not schedule the notification.');reminderStatus.textContent=`Notification scheduled for ${formatClock(notifyAt)}.`;setTimeout(closeReminder,900)}catch(error){reminderStatus.textContent=error.message||'Could not schedule the notification.';pushReminderButton.disabled=false}}
form.addEventListener('submit',event=>{event.preventDefault();const stop=stops.find(item=>item.code===stopSelect.value);if(!stop)return;queries.push({id:crypto.randomUUID?.()||String(Date.now()),stopCode:stop.code,stopName:stop.name,direction:directionSelect.value,destination:escapeText(destinationInput.value)});saveQueries();destinationInput.value='';closeForm();refreshAll()});
reminderLead.addEventListener('change',()=>{customLead.hidden=reminderLead.value!=='custom';if(!customLead.hidden)customLead.querySelector('input').focus()});
reminderForm.addEventListener('submit',event=>{event.preventDefault();if(!pendingReminder)return;downloadCalendarReminder(pendingReminder.stopName,pendingReminder.tram,selectedLead());closeReminder()});
pushReminderButton.addEventListener('click',schedulePushReminder);
document.querySelector('#open-form').addEventListener('click',openForm);document.querySelectorAll('[data-open-form]').forEach(button=>button.addEventListener('click',openForm));document.querySelector('#close-form').addEventListener('click',closeForm);document.querySelector('#close-reminder').addEventListener('click',closeReminder);document.querySelector('#refresh-all').addEventListener('click',refreshAll);dialog.addEventListener('click',event=>{if(event.target===dialog)closeForm()});reminderDialog.addEventListener('click',event=>{if(event.target===reminderDialog)closeReminder()});
loadStops();refreshAll();setInterval(rerenderCountdowns,15000);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
