(()=>{
'use strict';
const VERSION='2.0.0-alpha.2',$=s=>document.querySelector(s);
let franchises=[],collections=[],cards=[],adjustFrame=0;
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16).slice(2);
function relation(card){const collection=collections.find(x=>x.id===card.collectionId),franchise=franchises.find(x=>x.id===collection?.franchiseId);return{collection,franchise}}
function opt(select,items,label){select.replaceChildren(new Option('Selecione',''));items.forEach(x=>select.add(new Option(label(x),x.id)))}
async function refresh(){[franchises,collections,cards]=await Promise.all(['franchises','collections','cards'].map(TCGDB.all));opt($('#collection-franchise'),franchises,x=>x.name);opt($('#card-collection'),collections,x=>x.name);opt($('#adjust-card'),cards,x=>x.name);renderLists();renderAdjust();renderPrintList()}
function row(title,sub,onDelete){const r=document.createElement('div');r.className='row';const d=document.createElement('div');const strong=document.createElement('strong');strong.textContent=title;const small=document.createElement('small');small.textContent=sub||'';d.append(strong,small);const b=document.createElement('button');b.textContent='Excluir';b.onclick=onDelete;r.append(d,b);return r}
function renderLists(){const fl=$('#franchise-list'),cl=$('#collection-list'),cal=$('#card-list');fl.replaceChildren();cl.replaceChildren();cal.replaceChildren();franchises.forEach(f=>fl.append(row(f.name,f.logo?'Com logo':'Sem logo',async()=>{await TCGDB.del('franchises',f.id);refresh()})));collections.forEach(c=>cl.append(row(c.name,franchises.find(f=>f.id===c.franchiseId)?.name||'',async()=>{await TCGDB.del('collections',c.id);refresh()})));cards.forEach(c=>cal.append(row(c.name,relation(c).collection?.name||'',async()=>{await TCGDB.del('cards',c.id);refresh()})))}
function renderAdjust(){const c=cards.find(x=>x.id===$('#adjust-card').value)||cards[0];if(!c){$('#adjust-front').replaceChildren();$('#adjust-back').replaceChildren();return}$('#adjust-card').value=c.id;const{collection,franchise}=relation(c);$('#adjust-front').replaceChildren(TCGRenderer.card({card:c,collection,franchise,side:'front'}));$('#adjust-back').replaceChildren(TCGRenderer.card({card:c,collection,franchise,side:'back'}));$('#art-fit').value=c.artLayout?.fit||'cover';$('#art-x').value=c.artLayout?.x??50;$('#art-y').value=c.artLayout?.y??50;$('#art-zoom').value=c.artLayout?.zoom??100;$('#show-top').checked=c.showTopNumber!==false}
function updateAdjustPreview(){const c=cards.find(x=>x.id===$('#adjust-card').value);if(!c)return;c.artLayout={fit:$('#art-fit').value,x:Number($('#art-x').value),y:Number($('#art-y').value),zoom:Number($('#art-zoom').value)};c.showTopNumber=$('#show-top').checked;if(adjustFrame)return;adjustFrame=requestAnimationFrame(()=>{adjustFrame=0;TCGRenderer.updateArt($('#adjust-front svg'),c)})}
function renderPrintList(){const box=$('#print-list');box.replaceChildren();cards.forEach(c=>{const r=document.createElement('div');r.className='row';const d=document.createElement('div');const strong=document.createElement('strong');strong.textContent=c.name;const small=document.createElement('small');small.textContent=relation(c).collection?.name||'';d.append(strong,small);const q=document.createElement('input');q.type='number';q.min='0';q.max='99';q.value=c.copies??1;q.style.width='80px';q.onchange=async()=>{c.copies=Math.max(0,Number(q.value)||0);await TCGDB.put('cards',c)};r.append(d,q);box.append(r)})}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.setAttribute('aria-selected',x===b));document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==b.dataset.tab)});
$('#franchise-form').onsubmit=async e=>{e.preventDefault();await TCGDB.put('franchises',{id:id(),name:$('#franchise-name').value.trim(),logo:$('#franchise-logo').files[0]||null});e.target.reset();refresh()};
$('#collection-form').onsubmit=async e=>{e.preventDefault();await TCGDB.put('collections',{id:id(),name:$('#collection-name').value.trim(),franchiseId:$('#collection-franchise').value,total:$('#collection-total').value.trim(),frontBackground:$('#collection-front').files[0]||null,backBackground:$('#collection-back').files[0]||null,theme:{badgeText:$('#collection-badge').value.trim()||'SP',primary:$('#collection-primary').value,secondary:$('#collection-secondary').value,icon:$('#collection-icon').files[0]||null},templateId:'village'});e.target.reset();refresh()};
$('#card-form').onsubmit=async e=>{e.preventDefault();await TCGDB.put('cards',{id:id(),name:$('#card-name').value.trim(),collectionId:$('#card-collection').value,number:$('#card-number').value.trim(),art:$('#card-art').files[0],artLayout:{fit:'cover',x:50,y:50,zoom:100},showTopNumber:true,copies:1});e.target.reset();refresh()};
$('#adjust-card').onchange=renderAdjust;
['#art-fit','#art-x','#art-y','#art-zoom','#show-top'].forEach(s=>$(s).oninput=updateAdjustPreview);
$('#save-adjust').onclick=async()=>{const c=cards.find(x=>x.id===$('#adjust-card').value);if(!c)return;await TCGDB.put('cards',c);$('#adjust-status').textContent='Ajustes salvos.'};
function prepare(side){const nodes=[];cards.forEach(c=>{const{collection,franchise}=relation(c);for(let i=0;i<(c.copies??1);i++)nodes.push(TCGRenderer.card({card:c,collection,franchise,side}))});TCGPrint.pages(nodes.map(n=>n.cloneNode(true)));const prev=$('#print-preview');prev.replaceChildren(...nodes.slice(0,9));prev.hidden=!nodes.length;$('#open-print').hidden=!nodes.length;$('#print-status').textContent=nodes.length?`${nodes.length} carta(s) preparada(s).`:'Nenhuma cópia selecionada.'}
$('#prepare-front').onclick=()=>prepare('front');$('#prepare-back').onclick=()=>prepare('back');$('#open-print').onclick=()=>window.print();$('#version').textContent=`v${VERSION}`;TCGDB.open().then(refresh).catch(e=>alert('Erro ao abrir banco: '+e.message));if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
