(()=>{
'use strict';
const VERSION='2.0.0-alpha.4',$=s=>document.querySelector(s);
let franchises=[],collections=[],cards=[],adjustFrame=0;
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16).slice(2);
function relation(card){const collection=collections.find(x=>x.id===card.collectionId),franchise=franchises.find(x=>x.id===collection?.franchiseId);return{collection,franchise}}
function opt(select,items,label){const current=select.value;select.replaceChildren(new Option('Selecione',''));items.forEach(x=>select.add(new Option(label(x),x.id)));if(items.some(x=>x.id===current))select.value=current}
async function refresh(){[franchises,collections,cards]=await Promise.all(['franchises','collections','cards'].map(TCGDB.all));opt($('#collection-franchise'),franchises,x=>x.name);opt($('#card-collection'),collections,x=>x.name);opt($('#adjust-card'),cards,x=>x.name);renderLists();renderAdjust();renderPrintList()}
function row(title,sub,onDelete){const r=document.createElement('div');r.className='row';const d=document.createElement('div');const strong=document.createElement('strong');strong.textContent=title;const small=document.createElement('small');small.textContent=sub||'';d.append(strong,small);const b=document.createElement('button');b.textContent='Excluir';b.onclick=onDelete;r.append(d,b);return r}
function renderLists(){const fl=$('#franchise-list'),cl=$('#collection-list'),cal=$('#card-list');fl.replaceChildren();cl.replaceChildren();cal.replaceChildren();franchises.forEach(f=>fl.append(row(f.name,f.logo?'Com logo':'Sem logo',async()=>{if(collections.some(c=>c.franchiseId===f.id))return alert('Exclua primeiro as coleções desta franquia.');await TCGDB.del('franchises',f.id);refresh()})));collections.forEach(c=>cl.append(row(c.name,`${franchises.find(f=>f.id===c.franchiseId)?.name||''} · ${c.theme?.variant||'soft'}`,async()=>{if(cards.some(card=>card.collectionId===c.id))return alert('Exclua primeiro as cartas desta coleção.');await TCGDB.del('collections',c.id);refresh()})));cards.forEach(c=>cal.append(row(c.name,relation(c).collection?.name||'',async()=>{await TCGDB.del('cards',c.id);refresh()})))}
function setLayout(prefix,layout,defaultFit){$(`#${prefix}-fit`).value=layout?.fit||defaultFit;$(`#${prefix}-x`).value=layout?.x??50;$(`#${prefix}-y`).value=layout?.y??50;$(`#${prefix}-zoom`).value=layout?.zoom??100}
function readLayout(prefix){return{fit:$(`#${prefix}-fit`).value,x:Number($(`#${prefix}-x`).value),y:Number($(`#${prefix}-y`).value),zoom:Number($(`#${prefix}-zoom`).value)}}
function selectedContext(){const card=cards.find(x=>x.id===$('#adjust-card').value)||cards[0];if(!card)return{};return{card,...relation(card)}}
function setTheme(collection){const t=collection?.theme||{};$('#theme-variant').value=t.variant||'soft';$('#theme-front-intensity').value=t.frontIntensity??30;$('#theme-back-intensity').value=t.backIntensity??22}
function readTheme(collection){const old=collection?.theme||{};return{...old,variant:$('#theme-variant').value,frontIntensity:Number($('#theme-front-intensity').value),backIntensity:Number($('#theme-back-intensity').value)}}
function renderAdjust(){const{card,collection,franchise}=selectedContext();if(!card){$('#adjust-front').replaceChildren();$('#adjust-back').replaceChildren();return}$('#adjust-card').value=card.id;$('#adjust-front').replaceChildren(TCGRenderer.card({card,collection,franchise,side:'front'}));$('#adjust-back').replaceChildren(TCGRenderer.card({card,collection,franchise,side:'back'}));setLayout('art',card.artLayout,'cover');setLayout('front',collection?.frontLayout,'cover');setLayout('back',collection?.backLayout,'cover');setLayout('logo',franchise?.logoLayout,'contain');setTheme(collection);$('#show-top').checked=card.showTopNumber!==false;$('#adjust-status').textContent=''}
function updateAdjustPreview({rerender=false}={}){const{card,collection,franchise}=selectedContext();if(!card)return;card.artLayout=readLayout('art');card.showTopNumber=$('#show-top').checked;if(collection){collection.frontLayout=readLayout('front');collection.backLayout=readLayout('back');collection.theme=readTheme(collection)}if(franchise)franchise.logoLayout=readLayout('logo');if(rerender){renderAdjust();return}if(adjustFrame)return;adjustFrame=requestAnimationFrame(()=>{adjustFrame=0;const front=$('#adjust-front svg'),back=$('#adjust-back svg');TCGRenderer.updateArt(front,card);TCGRenderer.updateCollection(front,back,collection);TCGRenderer.updateLogo(back,franchise)})}
function renderPrintList(){const box=$('#print-list');box.replaceChildren();cards.forEach(c=>{const r=document.createElement('div');r.className='row';const d=document.createElement('div');const strong=document.createElement('strong');strong.textContent=c.name;const small=document.createElement('small');small.textContent=relation(c).collection?.name||'';d.append(strong,small);const q=document.createElement('input');q.type='number';q.min='0';q.max='99';q.value=c.copies??1;q.style.width='80px';q.onchange=async()=>{c.copies=Math.max(0,Number(q.value)||0);await TCGDB.put('cards',c)};r.append(d,q);box.append(r)})}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.setAttribute('aria-selected',x===b));document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==b.dataset.tab)});
$('#franchise-form').onsubmit=async e=>{e.preventDefault();await TCGDB.put('franchises',{id:id(),name:$('#franchise-name').value.trim(),logo:$('#franchise-logo').files[0]||null,logoLayout:{fit:'contain',x:50,y:50,zoom:100}});e.target.reset();$('#franchise-status').textContent='Franquia salva.';refresh()};
$('#collection-form').onsubmit=async e=>{e.preventDefault();await TCGDB.put('collections',{id:id(),name:$('#collection-name').value.trim(),franchiseId:$('#collection-franchise').value,total:$('#collection-total').value.trim(),frontBackground:$('#collection-front').files[0]||null,backBackground:$('#collection-back').files[0]||null,frontLayout:{fit:'cover',x:50,y:50,zoom:100},backLayout:{fit:'cover',x:50,y:50,zoom:100},theme:{badgeText:$('#collection-badge').value.trim()||'SP',primary:$('#collection-primary').value,secondary:$('#collection-secondary').value,variant:$('#collection-variant').value,frontIntensity:Number($('#collection-front-intensity').value),backIntensity:Number($('#collection-back-intensity').value),icon:$('#collection-icon').files[0]||null},templateId:'village'});e.target.reset();$('#collection-primary').value='#557a45';$('#collection-secondary').value='#244b32';$('#collection-front-intensity').value=30;$('#collection-back-intensity').value=22;$('#collection-status').textContent='Coleção salva.';refresh()};
$('#card-form').onsubmit=async e=>{e.preventDefault();await TCGDB.put('cards',{id:id(),name:$('#card-name').value.trim(),collectionId:$('#card-collection').value,number:$('#card-number').value.trim(),art:$('#card-art').files[0],artLayout:{fit:'cover',x:50,y:50,zoom:100},showTopNumber:true,copies:1});e.target.reset();$('#card-status').textContent='Carta salva.';refresh()};
$('#adjust-card').onchange=renderAdjust;
['art','front','back','logo'].flatMap(p=>[`#${p}-fit`,`#${p}-x`,`#${p}-y`,`#${p}-zoom`]).concat(['#show-top','#theme-front-intensity','#theme-back-intensity']).forEach(s=>$(s).oninput=()=>updateAdjustPreview());
$('#theme-variant').onchange=()=>updateAdjustPreview({rerender:true});
$('#save-adjust').onclick=async()=>{const{card,collection,franchise}=selectedContext();if(!card)return;updateAdjustPreview();await Promise.all([TCGDB.put('cards',card),collection&&TCGDB.put('collections',collection),franchise&&TCGDB.put('franchises',franchise)].filter(Boolean));$('#adjust-status').textContent='Ajustes da carta, coleção e franquia salvos.'};
function prepare(side){const nodes=[];cards.forEach(c=>{const{collection,franchise}=relation(c);for(let i=0;i<(c.copies??1);i++)nodes.push(TCGRenderer.card({card:c,collection,franchise,side}))});TCGPrint.pages(nodes.map(n=>n.cloneNode(true)));const prev=$('#print-preview');prev.replaceChildren(...nodes.slice(0,9));prev.hidden=!nodes.length;$('#open-print').hidden=!nodes.length;$('#print-status').textContent=nodes.length?`${nodes.length} carta(s) preparada(s).`:'Nenhuma cópia selecionada.'}
$('#prepare-front').onclick=()=>prepare('front');$('#prepare-back').onclick=()=>prepare('back');$('#open-print').onclick=()=>window.print();$('#version').textContent=`v${VERSION}`;TCGDB.open().then(refresh).catch(e=>alert('Erro ao abrir banco: '+e.message));if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();