(()=>{
'use strict';
const VERSION='2.0.0-alpha.25',$=s=>document.querySelector(s);
let franchises=[],collections=[],cards=[],adjustFrame=0,preparedNodes=[],preparedPairs=[],preparedSide='front';
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16).slice(2);
async function migrateIntegratedDefault(){const key='vibecode-cartas-tcg-v2-integrated-v1';if(localStorage.getItem(key))return;const stored=await TCGDB.all('collections');await Promise.all(stored.filter(series=>!series.theme?.artBackdrop||series.theme.artBackdrop==='studio').map(series=>TCGDB.put('collections',{...series,theme:{...series.theme,artBackdrop:'integrated'}})));localStorage.setItem(key,'1')}
function relation(card){const collection=collections.find(x=>x.id===card.collectionId),franchise=franchises.find(x=>x.id===collection?.franchiseId);return{collection,franchise}}
function opt(select,items,label){const current=select.value;select.replaceChildren(new Option('Selecione',''));items.forEach(x=>select.add(new Option(label(x),x.id)));if(items.some(x=>x.id===current))select.value=current}
async function refresh(){[franchises,collections,cards]=await Promise.all(['franchises','collections','cards'].map(TCGDB.all));opt($('#collection-franchise'),franchises,x=>x.name);opt($('#card-collection'),collections,x=>x.name);opt($('#adjust-card'),cards,x=>x.name);renderLists();renderAdjust();renderPrintList()}
function row(title,sub,onDelete){const r=document.createElement('div');r.className='row';const d=document.createElement('div');const strong=document.createElement('strong');strong.textContent=title;const small=document.createElement('small');small.textContent=sub||'';d.append(strong,small);const b=document.createElement('button');b.textContent='Excluir';b.onclick=onDelete;r.append(d,b);return r}
function renderLists(){const fl=$('#franchise-list'),cl=$('#collection-list'),cal=$('#card-list');fl.replaceChildren();cl.replaceChildren();cal.replaceChildren();franchises.forEach(f=>fl.append(row(f.name,f.logo?'Com logo':'Sem logo',async()=>{if(collections.some(c=>c.franchiseId===f.id))return alert('Exclua primeiro as séries desta franquia.');await TCGDB.del('franchises',f.id);refresh()})));collections.forEach(c=>cl.append(row(c.name,`${franchises.find(f=>f.id===c.franchiseId)?.name||''} · ${c.theme?.variant||'soft'}`,async()=>{if(cards.some(card=>card.collectionId===c.id))return alert('Exclua primeiro as cartas desta série.');await TCGDB.del('collections',c.id);refresh()})));cards.forEach(c=>cal.append(row(c.name,relation(c).collection?.name||'',async()=>{await TCGDB.del('cards',c.id);refresh()})))}
function setLayout(prefix,layout,defaultFit){$(`#${prefix}-fit`).value=layout?.fit||defaultFit;$(`#${prefix}-x`).value=layout?.x??50;$(`#${prefix}-y`).value=layout?.y??50;$(`#${prefix}-zoom`).value=layout?.zoom??100}
function readLayout(prefix){return{fit:$(`#${prefix}-fit`).value,x:Number($(`#${prefix}-x`).value),y:Number($(`#${prefix}-y`).value),zoom:Number($(`#${prefix}-zoom`).value)}}
function selectedContext(){const card=cards.find(x=>x.id===$('#adjust-card').value)||cards[0];if(!card)return{};return{card,...relation(card)}}
function setTheme(collection){const t=collection?.theme||{};$('#theme-variant').value=t.variant||'soft';$('#theme-background-style').value=t.backgroundStyle||'halo';$('#theme-pattern-intensity').value=t.patternIntensity??22;$('#theme-art-backdrop').value=t.artBackdrop||'integrated';$('#theme-front-intensity').value=t.frontIntensity??30;$('#theme-back-intensity').value=t.backIntensity??22}
function readTheme(collection){const old=collection?.theme||{};return{...old,variant:$('#theme-variant').value,backgroundStyle:$('#theme-background-style').value,patternIntensity:Number($('#theme-pattern-intensity').value),artBackdrop:$('#theme-art-backdrop').value,frontIntensity:Number($('#theme-front-intensity').value),backIntensity:Number($('#theme-back-intensity').value)}}
function renderAdjust(){const{card,collection,franchise}=selectedContext();if(!card){$('#adjust-front').replaceChildren();$('#adjust-back').replaceChildren();return}$('#adjust-card').value=card.id;$('#adjust-front').replaceChildren(TCGRenderer.card({card,collection,franchise,side:'front'}));$('#adjust-back').replaceChildren(TCGRenderer.card({card,collection,franchise,side:'back'}));setLayout('art',card.artLayout,'cover');setLayout('front',collection?.frontLayout,'cover');setLayout('back',collection?.backLayout,'cover');setLayout('logo',franchise?.logoLayout,'contain');setTheme(collection);$('#adjust-status').textContent=''}
function updateAdjustPreview({rerender=false}={}){const{card,collection,franchise}=selectedContext();if(!card)return;card.artLayout=readLayout('art');if(collection){collection.frontLayout=readLayout('front');collection.backLayout=readLayout('back');collection.theme=readTheme(collection)}if(franchise)franchise.logoLayout=readLayout('logo');if(rerender){renderAdjust();return}if(adjustFrame)return;adjustFrame=requestAnimationFrame(()=>{adjustFrame=0;const front=$('#adjust-front svg'),back=$('#adjust-back svg');TCGRenderer.updateArt(front,card);TCGRenderer.updateCollection(front,back,collection);TCGRenderer.updateLogo(back,franchise)})}
function renderPrintList(){const box=$('#print-list');box.replaceChildren();cards.forEach(c=>{const r=document.createElement('div');r.className='row';const d=document.createElement('div');const strong=document.createElement('strong');strong.textContent=c.name;const small=document.createElement('small');small.textContent=relation(c).collection?.name||'';d.append(strong,small);const q=document.createElement('input');q.type='number';q.min='0';q.max='99';q.value=c.copies??1;q.style.width='80px';q.onchange=async()=>{c.copies=Math.max(0,Number(q.value)||0);await TCGDB.put('cards',c)};r.append(d,q);box.append(r)})}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.setAttribute('aria-selected',x===b));document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==b.dataset.tab)});
$('#franchise-form').onsubmit=async e=>{e.preventDefault();await TCGDB.put('franchises',{id:id(),name:$('#franchise-name').value.trim(),logo:$('#franchise-logo').files[0]||null,logoLayout:{fit:'contain',x:50,y:50,zoom:100}});e.target.reset();$('#franchise-status').textContent='Franquia salva.';refresh()};
$('#collection-form').onsubmit=async e=>{e.preventDefault();await TCGDB.put('collections',{id:id(),name:$('#collection-name').value.trim(),franchiseId:$('#collection-franchise').value,frontBackground:$('#collection-front').files[0]||null,backBackground:$('#collection-back').files[0]||null,frontLayout:{fit:'cover',x:50,y:50,zoom:100},backLayout:{fit:'cover',x:50,y:50,zoom:100},theme:{primary:$('#collection-primary').value,secondary:$('#collection-secondary').value,variant:$('#collection-variant').value,backgroundStyle:$('#collection-background-style').value,patternIntensity:Number($('#collection-pattern-intensity').value),artBackdrop:$('#collection-art-backdrop').value,frontIntensity:Number($('#collection-front-intensity').value),backIntensity:Number($('#collection-back-intensity').value)},templateId:'village'});e.target.reset();$('#collection-primary').value='#557a45';$('#collection-secondary').value='#244b32';$('#collection-background-style').value='halo';$('#collection-pattern-intensity').value=22;$('#collection-art-backdrop').value='integrated';$('#collection-front-intensity').value=30;$('#collection-back-intensity').value=22;$('#collection-status').textContent='Série salva.';refresh()};
$('#card-form').onsubmit=async e=>{e.preventDefault();await TCGDB.put('cards',{id:id(),name:$('#card-name').value.trim(),collectionId:$('#card-collection').value,art:$('#card-art').files[0],artLayout:{fit:'cover',x:50,y:50,zoom:100},copies:1});e.target.reset();$('#card-status').textContent='Carta salva.';refresh()};
$('#import-run').onclick=async()=>{const file=$('#import-file').files[0],status=$('#import-status'),button=$('#import-run');if(!file){status.textContent='Selecione um arquivo JSON.';return}button.disabled=true;status.textContent='Validando arquivo…';try{const imported=await TCGImporter.parse(await file.text()),replace=$('#import-mode').value==='replace';await TCGDB.importAll(imported,{replace});await refresh();status.textContent=`Importação concluída: ${imported.franchises.length} franquia(s), ${imported.collections.length} série(s) e ${imported.cards.length} carta(s).`}catch(error){status.textContent='Erro: '+error.message}finally{button.disabled=false}};
$('#adjust-card').onchange=renderAdjust;
['art','front','back','logo'].flatMap(p=>[`#${p}-fit`,`#${p}-x`,`#${p}-y`,`#${p}-zoom`]).concat(['#theme-front-intensity','#theme-back-intensity']).forEach(s=>$(s).oninput=()=>updateAdjustPreview());
['#theme-variant','#theme-background-style','#theme-art-backdrop'].forEach(s=>$(s).onchange=()=>updateAdjustPreview({rerender:true}));$('#theme-pattern-intensity').oninput=()=>updateAdjustPreview({rerender:true});
$('#save-adjust').onclick=async()=>{const{card,collection,franchise}=selectedContext();if(!card)return;updateAdjustPreview();await Promise.all([TCGDB.put('cards',card),collection&&TCGDB.put('collections',collection),franchise&&TCGDB.put('franchises',franchise)].filter(Boolean));$('#adjust-status').textContent='Ajustes da carta, série e franquia salvos.'};
function prepare(side){const nodes=[];cards.forEach(c=>{const{collection,franchise}=relation(c);for(let i=0;i<(c.copies??1);i++)nodes.push(TCGRenderer.card({card:c,collection,franchise,side}))});preparedNodes=nodes;preparedSide=side;const mirror=side==='back';TCGPrint.pages(nodes.map(n=>n.cloneNode(true)),{mirror});const previewNodes=nodes.slice(0,9).map((node,index)=>TCGPrint.place(node,index,mirror));const prev=$('#print-preview');prev.replaceChildren(...previewNodes);prev.hidden=!nodes.length;$('#open-print').hidden=!nodes.length;$('#download-pdf').hidden=!nodes.length;$('#print-status').textContent=nodes.length?`${nodes.length} carta(s) preparada(s). ${mirror?'Os versos foram espelhados por linha para alinhar com as frentes. ':''}Use “Baixar PDF exato” para preservar cores e dimensões.`:'Nenhuma cópia selecionada.'}
function prepareFold(){const pairs=[];cards.forEach(card=>{const{collection,franchise}=relation(card);for(let i=0;i<(card.copies??1);i++)pairs.push({back:TCGRenderer.card({card,collection,franchise,side:'back',bleedSide:'right'}),front:TCGRenderer.card({card,collection,franchise,side:'front',bleedSide:'left'})})});preparedPairs=pairs;preparedSide='fold';preparedNodes=[];const preview=pairs.slice(0,4).flatMap(pair=>[pair.back,pair.front]);const prev=$('#print-preview');prev.replaceChildren(...preview);prev.hidden=!pairs.length;$('#open-print').hidden=true;$('#download-pdf').hidden=!pairs.length;$('#print-status').textContent=pairs.length?`${pairs.length} carta(s) dobrável(is) preparada(s). Verso à esquerda, frente à direita.`:'Nenhuma cópia selecionada.'}
function printScale(){const measured=Number($('#print-measured-reference').value);if(!Number.isFinite(measured)||measured<48||measured>52)throw new Error('A medida de calibração deve ficar entre 48 e 52 mm.');localStorage.setItem('vibecode-cartas-print-reference',String(measured));return 50/measured}
const savedReference=Number(localStorage.getItem('vibecode-cartas-print-reference'));if(savedReference>=48&&savedReference<=52)$('#print-measured-reference').value=String(savedReference);
$('#prepare-fold').onclick=prepareFold;$('#prepare-front').onclick=()=>prepare('front');$('#prepare-back').onclick=()=>prepare('back');$('#download-pdf').onclick=async()=>{const button=$('#download-pdf');button.disabled=true;try{const scale=printScale(),progress=(current,total)=>{$('#print-status').textContent=`Gerando PDF: ${current}/${total}…`};if(preparedSide==='fold')await TCGPdf.downloadFold(preparedPairs,'cartas-dobraveis.pdf',progress,{scale});else await TCGPdf.download(preparedNodes,`cartas-${preparedSide}.pdf`,progress,{mirror:preparedSide==='back',scale});$('#print-status').textContent=`PDF calibrado gerado. Compensação: ${(scale*100).toFixed(2)}%. Imprima em escala 100% / tamanho real.`}catch(error){$('#print-status').textContent='Erro ao gerar PDF: '+error.message}finally{button.disabled=false}};$('#open-print').onclick=()=>window.print();$('#version').textContent=`v${VERSION}`;TCGDB.open().then(async()=>{await migrateIntegratedDefault();await refresh()}).catch(e=>alert('Erro ao abrir banco: '+e.message));if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
