window.TCGImporter=(()=>{
  'use strict';
  const FORMAT='vibecode-cartas-tcg-v2',VERSION=2,FITS=new Set(['cover','contain','fill']),VARIANTS=new Set(['soft','ornate','clean']),BACKGROUNDS=new Set(['halo','rays','waves','geometric','confetti','topographic','paper']),BACKDROPS=new Set(['integrated','studio','halo','stage','clean','none']);
  const fail=message=>{throw new Error(message)};
  const object=(value,path)=>value&&typeof value==='object'&&!Array.isArray(value)?value:fail(`${path} deve ser um objeto.`);
  const text=(value,path,{required=false}={})=>{if(value==null&&!required)return'';if(typeof value!=='string'||(required&&!value.trim()))fail(`${path} deve ser um texto${required?' não vazio':''}.`);return value.trim()};
  const number=(value,path,defaultValue,min,max)=>{if(value==null)return defaultValue;const n=Number(value);if(!Number.isFinite(n)||n<min||n>max)fail(`${path} deve ser um número entre ${min} e ${max}.`);return n};
  function layout(value,path,defaultFit){const v=value==null?{}:object(value,path),fit=v.fit??defaultFit;if(!FITS.has(fit))fail(`${path}.fit deve ser cover, contain ou fill.`);return{fit,x:number(v.x,`${path}.x`,50,0,100),y:number(v.y,`${path}.y`,50,0,100),zoom:number(v.zoom,`${path}.zoom`,100,50,250)}}
  async function image(value,path,{required=false}={}){if(value==null||value===''){if(required)fail(`${path} é obrigatório.`);return null}if(typeof value!=='string'||!/^data:image\/[a-z0-9.+-]+(?:;[^,]*)?,/i.test(value))fail(`${path} deve ser uma data URL de imagem.`);const response=await fetch(value);const blob=await response.blob();if(!blob.type.startsWith('image/'))fail(`${path} não contém uma imagem válida.`);return blob}
  function unique(records,name){const ids=new Set();records.forEach((record,index)=>{const id=text(record?.id,`${name}[${index}].id`,{required:true});if(ids.has(id))fail(`${name} contém o ID duplicado "${id}".`);ids.add(id)});return ids}
  async function parse(source){
    let root;try{root=JSON.parse(source)}catch(error){fail(`JSON inválido: ${error.message}`)}
    object(root,'raiz');if(root.format!==FORMAT)fail(`format deve ser "${FORMAT}".`);if(root.version!==1&&root.version!==VERSION)fail(`version deve ser 1 ou ${VERSION}.`);
    const legacy=root.version===1,seriesInput=legacy?root.collections:root.series,seriesPath=legacy?'collections':'series';
    if(!Array.isArray(root.franchises))fail('franchises deve ser uma lista.');if(!Array.isArray(seriesInput))fail(`${seriesPath} deve ser uma lista.`);if(!Array.isArray(root.cards))fail('cards deve ser uma lista.');
    const franchiseIds=unique(root.franchises,'franchises'),seriesIds=unique(seriesInput,seriesPath);unique(root.cards,'cards');
    const franchises=[];for(let i=0;i<root.franchises.length;i++){const p=`franchises[${i}]`,v=object(root.franchises[i],p);franchises.push({id:text(v.id,`${p}.id`,{required:true}),name:text(v.name,`${p}.name`,{required:true}),logo:await image(v.logo,`${p}.logo`),logoLayout:layout(v.logoLayout,`${p}.logoLayout`,'contain')})}
    const collections=[];for(let i=0;i<seriesInput.length;i++){const p=`${seriesPath}[${i}]`,v=object(seriesInput[i],p),franchiseId=text(v.franchiseId,`${p}.franchiseId`,{required:true});if(!franchiseIds.has(franchiseId))fail(`${p}.franchiseId referencia uma franquia inexistente.`);const t=v.theme==null?{}:object(v.theme,`${p}.theme`),variant=t.variant??'soft',backgroundStyle=t.backgroundStyle??'halo',artBackdrop=t.artBackdrop??'integrated';if(!VARIANTS.has(variant))fail(`${p}.theme.variant deve ser soft, ornate ou clean.`);if(!BACKGROUNDS.has(backgroundStyle))fail(`${p}.theme.backgroundStyle não é válido.`);if(!BACKDROPS.has(artBackdrop))fail(`${p}.theme.artBackdrop não é válido.`);collections.push({id:text(v.id,`${p}.id`,{required:true}),name:text(v.name,`${p}.name`,{required:true}),franchiseId,frontBackground:await image(v.frontBackground,`${p}.frontBackground`),backBackground:await image(v.backBackground,`${p}.backBackground`),frontLayout:layout(v.frontLayout,`${p}.frontLayout`,'cover'),backLayout:layout(v.backLayout,`${p}.backLayout`,'cover'),theme:{primary:text(t.primary,`${p}.theme.primary`)||'#557a45',secondary:text(t.secondary,`${p}.theme.secondary`)||'#244b32',variant,backgroundStyle,patternIntensity:number(t.patternIntensity,`${p}.theme.patternIntensity`,22,0,60),artBackdrop,frontIntensity:number(t.frontIntensity,`${p}.theme.frontIntensity`,30,0,100),backIntensity:number(t.backIntensity,`${p}.theme.backIntensity`,22,0,100)},templateId:text(v.templateId,`${p}.templateId`)||'village'})}
    const cards=[];for(let i=0;i<root.cards.length;i++){const p=`cards[${i}]`,v=object(root.cards[i],p),seriesId=text(legacy?v.collectionId:v.seriesId,`${p}.${legacy?'collectionId':'seriesId'}`,{required:true});if(!seriesIds.has(seriesId))fail(`${p}.${legacy?'collectionId':'seriesId'} referencia uma série inexistente.`);cards.push({id:text(v.id,`${p}.id`,{required:true}),name:text(v.name,`${p}.name`,{required:true}),collectionId:seriesId,art:await image(v.art,`${p}.art`,{required:true}),artLayout:layout(v.artLayout,`${p}.artLayout`,'cover'),copies:Math.trunc(number(v.copies,`${p}.copies`,1,0,99))})}
    return{franchises,collections,cards}
  }
  return{parse,FORMAT,VERSION};
})();
